### ISSUE TITLE
Invalid patron email fails when user_attributes is nil

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/requests#1004]
There's a `no [] for nil` error on this template https://github.com/pulibrary/requests/blob/756c5a7fb7947a432646ab438f4752902c5e556d/app/views/requests/request_mailer/invalid_illiad_patron_email.html.erb#L7

Not sure if there should be some nil checking in there or more guards in https://github.com/pulibrary/requests/blob/756c5a7fb7947a432646ab438f4752902c5e556d/app/models/requests/illiad_transaction_client.rb#L23

Honeybadger notice: https://app.honeybadger.io/projects/54399/faults/39796981 -- NOTE this is not alma-related

**Comment by hectorcorrea** [comment]
Notice that the error is triggered when rendering  an email for an invalid ILLiad request (`request_mailer_invalid_illiad_patron_email_html_erb`) so this might be a rather infrequent issue.
