### ISSUE TITLE
request form errors on marquand stacks holding

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/requests#1005]
page erroring: https://catalog-alma-qa.princeton.edu/requests/9988425703506421?mfhd=22228691340006421&source=pulsearch

honeybadger notice: https://app.honeybadger.io/projects/54399/faults/80065567

It's the "stacks" holding on this record: https://catalog-alma-qa.princeton.edu/catalog/9988425703506421. The form for the other holding loads fine.

**Comment by kevinreiss** [comment]
I think this is likely due to a config issue related to the Clancy api possibly. Marquand recap holdings load fine.

**Comment by carolyncole** [comment]
fixed by https://github.com/pulibrary/orangelight/pull/2548

**Comment by kevinreiss** [comment]
Closing.
