### ISSUE TITLE
Status shows Not Available but it is green 

### ISSUE THREAD

**Issue by christinach** [pulibrary/requests#1007]
https://catalog.princeton.edu/requests/9976174773506421?mfhd=22170509880006421&source=pulsearch

![Screen Shot 2021-06-29 at 2 50 38 PM](https://user-images.githubusercontent.com/9905193/123851603-63e71400-d8e9-11eb-8450-5f9392b18167.png)

**Comment by kevinreiss** [comment]
This is a really outlying record. It's an Ipad device that has no item record. Not sure how to handle this one.

**Comment by kevinreiss** [comment]
Need to discuss with circulation management on how to handle records that are for devices like iPads and Kindles.

**Comment by kevinreiss** [comment]
Now this is going to fallback option because there is no item data. Confirm with circulation that this is a good outcome.
