### ISSUE TITLE
Form Conditional Cleanup

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#101]
Review view partials and form helpers to reduce reliance on conditionals and leverage the list of services attached to a given requestable object to decide what form elements and sets of labels need to be rendered. This should also reduce the footprint of the codebase that needs to be tested. The application helper is the worst culprit here.

**Comment by sdellis** [comment]
So, I am a little unclear of what is supposed to happen here. Is the first step to move conditionals in the form into helper functions? Then the second step is to test those functions?

So, for example, something like this:
```
<% if requestable.services.include?('recap_edd') %>
  <br/>
  <%= radio_button_tag "requestable[][delivery_mode_#{requestable.item[:id]}]", "edd", false, data: { target: "#fields-eed__#{requestable.item[:id]}" }, 'aria-expanded' => 'false', 'aria-controls' => "fields-eed__#{requestable.item[:id]}", class: 'control-label' %>
  <%= label_tag "requestable__type_recap_edd_#{requestable.item[:id]}", "Electronic Delivery", class: 'control-label' %>
  <br/><small id="requestable__type_recap_edd_caption_<%= requestable.item[:id] %>" class="form-text text-muted"><%= I18n.t('requests.recap_edd.brief_msg') %></small>
  <%= render partial: "edd_fields", locals: { requestable: requestable } %>
<% end %>
```
would become a `display_edd_fields` helper function?  And then I should test the output of that helper to make sure the appropriate fields were rendered?

To add to my confusion, I'm looking at the examples that were stubbed in the helpers spec, and it seems that these scenarios are already being tested. For example, [this one](https://github.com/pulibrary/requests/blob/development/spec/helpers/requests/application_helper_spec.rb#L43-L46) looks like it would be a duplicate test of [this one](https://github.com/pulibrary/requests/blob/development/spec/models/requests/request_spec.rb#L607-L613). I'm not clear on why we would want to do that.
