### ISSUE TITLE
The new recap locations no longer have holding library, so in library use is not working

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#1021]
https://catalog-alma-qa.princeton.edu/requests/99122455097406421?mfhd=22477871910006421&source=pulsearch

https://github.com/pulibrary/requests/blob/23ac04c99952f5c22d714ee4be9d432e927a4257/app/models/requests/requestable.rb#L206

**Comment by kevinreiss** [comment]
I spoke with @christinach and this will be configured for remote_storage locations in bibdata. For local testing we can just add it to a local bibdata. The updates to persist it for remote_storage location will be in bibdata-alma soon.

**Comment by carolyncole** [comment]
This was fixed by @christinach in bibdata.  Thanks @christinach!
