### ISSUE TITLE
The location display seems off

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#1034]
https://catalog-alma-qa.princeton.edu/requests/99120681043506421?mfhd=22265665700006421&source=pulsearch

We are just showing Stacks 
![Screen Shot 2021-07-16 at 8 49 54 AM](https://user-images.githubusercontent.com/1599081/125950507-3c4bc651-557e-4ef7-abb8-3a1c06af212a.png)

**Comment by kevinreiss** [comment]
Yes, I think we have now to inject the Library Name Label in front on the shelf location label.
