### ISSUE TITLE
Hold Requests don't change Alma Base Status So we should give the user some feedback when they request an item twice

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#1040]
This is a potential user interface problem. When a patron places a "pick-up request" on an item the hold request created does not change the base status of the item, it's still marked as "Item In Place" in Alma. The item does not change to "not in place" until the item is pulled and charged at the circulation desk fulfilling the hold. This can potentially let items with active holds be available for request to be available for several days if the request comes in over the weekend in certain locations. In Voyager we marked items available in Blacklight when there was an active hold on them. 

The alma item record returns the attribute "<requested>true</requested>" when there is a hold request active for an item, we could use that to at least keep the users from submitting requests on items that have an outstanding hold. If this is something we want to leverage I believe we'll need it to bibdata response in availability.json.

**Comment by carolyncole** [comment]
We should give user some feedback and not send the recap problem email
