### ISSUE TITLE
Rename scsb? methods

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#1042]
At the request level scsb? means at a partner library
At the requestable level scsb? means at ReCAP

We should rename the two methods.  I'm thinking `partner_owned?` for the request level and `recap?` for the requestable level

**Comment by hackartisan** [comment]
feel free to add this (and any other ticket) to the refactorama project board

**Comment by carolyncole** [comment]
The code is actually using scsb? in the same way in each location, just slightly different logic?
