### ISSUE TITLE
Update Fixtures

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#106]
Make sure records used as example cases here are stored as fixtures https://docs.google.com/spreadsheets/d/1yjHqjtl_Bs_MiKKu0FzjdIIe2NzgskVeBlJsWPTkgN0/edit#gid=0

**Comment by sdellis** [comment]
Fixed by [Orangelight commit](https://github.com/pulibrary/orangelight/commit/78ca8c0505b798c23a36bde3bb5ecebb7d27341c).
