### ISSUE TITLE
Harvard items should support EDD

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#1066]
This is happening because the collection code is not in this list: https://github.com/pulibrary/requests/blob/main/app/models/requests/requestable.rb#L294

**Comment by carolyncole** [comment]
@kevinreiss Do we know if there are multiple collections in the Harvard data? The test one I am looking at has a code of "HW",  which I can add to the list of collections available for EDD.  It would be nice to know the complete list.

**Comment by carolyncole** [comment]
There is at least one more collection code `FL` in addition to the `HW` that most things seem to be in.  Do we know which codes can be digitized?

**Comment by kevinreiss** [comment]
These are codes in the projects docs eligible for EDD from HL

AH DL FL GUT HB HC HJ HK HL HS HW HY MCZ ML TZ WL
