### ISSUE TITLE
Bound with titles (in ReCAP) are not able to be requested in the catalog.

### ISSUE THREAD

**Issue by christinach** [pulibrary/requests#1077]
Marie Wange Connelly reported in the catalog channel:
"Bound with titles (in ReCAP) are not able to be requested in the catalog. I have come across bound with titles that when requested by users behaves strangely. If you go to the bound with record "Multi title collection .... and where the barcode is attached when you get to the request page it says "Available-In process" which they are not these items are in ReCAP."

example with 28 titles: https://catalog.princeton.edu/catalog/99124962843506421

**Comment by carolyncole** [comment]
@christinach @mzelesky I get the following when looking up the item in SCSB
```
byebug) availability_data
[{"itemBarcode"=>"", "itemAvailabilityStatus"=>nil, "errorMessage"=>"Bib Id doesn't exist in SCSB database.", "collectionGroupDesignation"=>nil}]
(byebug) system_id
"99124962843506421"
(byebug)  scsb_owning_institution(scsb_location)
"PUL"
```

**Comment by carolyncole** [comment]
In Process is correct for this item given that SCSB is returning that the item does not exist.

**Comment by carolyncole** [comment]
![Screen Shot 2021-09-08 at 8 41 43 AM](https://user-images.githubusercontent.com/1599081/132511093-1ce62e8f-175f-44a5-bfbc-f617dc2b9570.png)

**Comment by christinach** [comment]
Is it possible that this item is not any more in recap? 12 days ago when I posted the comment @mzelesky looked at it and it was in recap.
