### ISSUE TITLE
Referring Record Page Info Lost on Barcode Auth Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#109]
When a barcode user mistypes their barcode or lastname and gets an error in the UI to correct the form loses the information about which bib ID/mfhd combo they traveled from to get to the request form. Right now this is based on looking at the referring URL value in the Rails request object. Making sure this data sticks around should probably be done in a different fashion.

**Comment by kevinreiss** [comment]
See commit for the hack currently doing this https://github.com/pulibrary/orangelight/commit/f54ea01dd7b64e82853e4ceed8a1198f9a1537ef

**Comment by sdellis** [comment]
@kevinreiss, this branch fixes this: https://github.com/pulibrary/orangelight/compare/requests-issue-109

This is the simplest approach and works. If 👍 then I will submit a PR to Orangelight.

**Comment by kevinreiss** [comment]
Resolved. Thanks.
