### ISSUE TITLE
Temporary locations are not being shown in requests

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#1098]
We do not see the temp  location here:
https://catalog.princeton.edu/requests/99117500093506421?mfhd=22667477540006421
![Screen Shot 2021-11-04 at 9 41 24 AM](https://user-images.githubusercontent.com/1599081/140323832-62a8541c-0ea3-4dce-96a3-89370b55f1a3.png)

See the temp location in the catalog:
![Screen Shot 2021-11-04 at 9 42 06 AM](https://user-images.githubusercontent.com/1599081/140323923-7eec7611-88d4-42dc-a4ca-94f68f2b8772.png)

**Comment by christinach** [comment]
this is fixed
