### ISSUE TITLE
Cannot Submit an EDD for Annex Serial Item

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#1103]
Example Record: https://catalog.princeton.edu/requests/9999657563506421?mfhd=22741559450006421.

When selecting the EDD option for Annex serial items you cannot place a request. 

<img width="1594" alt="Screen Shot 2021-12-09 at 9 24 23 PM" src="https://user-images.githubusercontent.com/278825/145513878-329a28b0-7d19-436e-addf-5f5b7496285e.png">

**Comment by sandbergja** [comment]
Closing in favor of https://github.com/pulibrary/orangelight/issues/2950, since this code is now in orangelight
