### ISSUE TITLE
Display Three Hour Reserve Location Label

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#1105]
This issue is obscured because of temp location display issues being worked on here: https://github.com/pulibrary/bibdata/pull/1734. The "available" copy on this record (the other is sequestered for CDL) https://catalog.princeton.edu/catalog/99116991823506421 is in a three hour loan location that staff says can actually be charged out to patron. When we fix the temp location problem we need to indicate in some way that the item is available for this sort of loan. Right now the request form shows only a digitization request option https://catalog.princeton.edu/requests/99116991823506421?mfhd=22724878140006421. It should not be physically requestable, but we should somehow note it's available for 3-hr loan if we can.

**Comment by kevinreiss** [comment]
This can likely be closed when the temp location indexing fix goes into production.

**Comment by kevinreiss** [comment]
The example record looks exactly as I think it should after the temp changes in staging.

**Comment by christinach** [comment]
https://catalog-staging.princeton.edu/catalog/99116991823506421 @kevinreiss can we close this issue?

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/bibdata/pull/1734
