### ISSUE TITLE
Digitization Request is not accepted

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#1107]
https://catalog.princeton.edu/requests/994268243506421?mfhd=22698167790006421

When you try to make a digitization request on a selected volume you get stuck in a loop with the attached error. Physical item requests work fine. 

<img width="1647" alt="Screen Shot 2022-02-04 at 3 20 54 PM" src="https://user-images.githubusercontent.com/278825/152604939-c3e405f6-fd62-427c-8628-77fc45456f43.png">

**Comment by carolyncole** [comment]
@kevinreiss Do we really have a workflow for annex digitization?  This may be a UI issue.  The type annex_edd is unrecognized...  I do not see any references to it in the code base, so my guess is the UI is showing an option we do not support.

**Comment by kevinreiss** [comment]
Spoke with resource sharing staff about this and they said any digitization requests for annex materials can just be submitted to illiad like we do with any non recap material digitization requests.

**Comment by sandbergja** [comment]
Closing in favor of https://github.com/pulibrary/orangelight/issues/2950, since this code is now in orangelight
