### ISSUE TITLE
Handle lewis$resterm and RES_SHARE$IN_RS_REQ better

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/requests#1120]
These are indexed with a holdings_1_display like so:
```
{"RES_SHARE$IN_RS_REQ"=>{"location_code"=>"RES_SHARE$IN_RS_REQ", "current_location"=>"Lending Resource Sharing Requests", "current_library"=>"Resource Sharing Library", "call_number"=>"KJC985 .S436 1973", "call_number_browse"=>"KJC985 .S436 1973", "items"=>[{"holding_id"=>"22538008330006421", "id"=>"23538008320006421", "status_at_load"=>"0", "barcode"=>"32101105262040", "copy_number"=>"1"}], "etas_limited_access"=>false}}
```

These still show the request button, but then throw an error when the user attempts to actually request them, since this line searches the holdings hash by holding_id rather than location: https://github.com/pulibrary/requests/blob/615e49faaea6852f87b5df2945b210f6451fe629/app/models/requests/request.rb#L288

Here are some example MMS IDs:

- 99123281083506421
- 9915946413506421
- 9910469743506421
- 9996919313506421
- 9963707933506421
- 9967985873506421
- 99125418905006421
- 9969028213506421
- 9945736713506421

**Comment by carolyncole** [comment]
There may be an issue with the MFHD that is being passed into requests.  This could be either a orangelight of bibdata issue...

**Comment by carolyncole** [comment]
Reserve Term locations are less straight forward. They should not be using those and a policy decision needs to be made.

**Comment by christinach** [comment]
RES_SHARE$IN_RS_REQ is handled in bibdata https://github.com/pulibrary/bibdata/pull/1826
lewis$resterm is handled in the location configuration on the Alma side
