### ISSUE TITLE
Handle Case when user type has zero request options

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#1125]
Companion to #1122. Instead of "help me get it" we need to create a fallback option for when a patron would have no requestable options for an item. This doesn't happen for PUL net ID holders, but will happen when we allow users who do not have net IDs to resume requesting items. In this instance the form should just give them a message there are no requestable copies. I have asked circ management for the wording they want.

**Comment by carolyncole** [comment]
@kevinreiss For Alma login we show what is below.  Can we close this ticket?  ![Screen Shot 2022-05-02 at 11.09.55 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/cd1560f5-a4f5-48f8-9b4d-050c5a92ccf2)

**Comment by carolyncole** [comment]
Completed during the Alma work
