### ISSUE TITLE
Integration Tests for Form Behaviors

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#113]
Set up some integration tests that utilize capybara to test the operation of the request form. We'll need to test each of the user types:

1. CAS
2. Barcode
3. Access User

Right now testing scenarios 1 + 2 is blocked https://github.com/pulibrary/requests/pull/81 because I could not get the sign-in emulation methods https://github.com/pulibrary/requests/pull/81/files#diff-a24222255d6d1c1e3163556c48427bc7R28 to fire properly. Scenario 3 can be tested because that doesn't require any authentication only manipulation of the form fields. 

Things to test:

1. Error messaging
2. Form element states for checkbox and submit button labels.
3. Confirmation messages upon a successful/failed request.

**Comment by sdellis** [comment]
So, I ran into an interesting problem when testing the submission of an access user request. This works fine in the browser, but you will get an error when running the spec: 
```
#Access users cannot use recap service directly
      @services << Requests::Generic.new(@submission)
     
     ActionController::UnknownFormat:
...
``` 
Recap items work differently for Access users in that they don't use the service directly but via  moderated email submission.

When commenting out this line, it passes:
https://github.com/pulibrary/requests/blob/issue-113/spec/features/requests/request_spec.rb#L42

**Comment by kevinreiss** [comment]
Oh, the click_button ajax is hitting a form that does an ajax happens so the test suite needs a js driver. I forgot to include that:

https://github.com/pulibrary/requests/commit/678c786cc64af06dfb79583fc022f406118d8802

Should run fine now.

**Comment by sdellis** [comment]
It seems this was completed. Is there anything reason we need to keep this open?

**Comment by kevinreiss** [comment]
We should make sure we add scenarios that cover the form state and the form submit button message for both single and multi-holding items (perhaps we can adopt some of the multi-holding options from other specs as examples).
