### ISSUE TITLE
Reserve item should offer delivery methods/pickup locations

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#143]
See: requests/8179402

"Request this Item" button and select checkbox display without delivery locations. If no other copies are loanable at Princeton (as is the example case), it should allow BD (and ILL?), but not Recall.

**Comment by sdellis** [comment]
For now, we will disable checkbox and Request button until policy questions are sorted out.

**Comment by sdellis** [comment]
This works in my tests to determine if something is on reserve... @kevinreiss are there any other `temp_loc` strings that can indicate a reserve item that isn't caught by that regex?

```
def on_reserve?
    false
    if has_item_data? && !item[:temp_loc].blank?
      if item[:temp_loc].match(/^res/)
          true
      end
    end
end
```

**Comment by kevinreiss** [comment]
Won't this method as written always return "false"? See https://bibdata.princeton.edu/availability?id=8179402. Reserve items have a On Reserve key flagged as "Y".

**Comment by sdellis** [comment]
No, that method works for me in my dev environment. However, I agree that we should be using the "on_reserve" value from bib_data. The problem is that it doesn't come through, and I think I've tracked it down to a bug in the load_items method. I will work on fixing that so we can use that data.

**Comment by kevinreiss** [comment]
We are relying on the mfhd call to (in theory) get a fuller representation of the item level data for the holding.

For the single mfhd 7946042 on this example we are getting:

https://bibdata.princeton.edu/availability?mhd=7946042

**Comment by sdellis** [comment]
Let me know if this should be a quick fix in marc_liberation, or if I should try to use a regex/starts_with check on the `temp_loc` field as a temporary workaround to identify `on_reserve` items.

**Comment by kevinreiss** [comment]
See https://github.com/pulibrary/voyager_helpers/pull/62. Once merged we need to cut a new release and advance marc_liberation to that release.
