### ISSUE TITLE
Add better error handling around failure in bibdata patron service

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#151]
> have the whole form generation stop and produce an error if line 45 in the controller that invokes the "current_patron" method returns false

**Comment by kevinreiss** [comment]
We will need to update the views for this controller action to produce a reasonable error message in this instance. There are basically two categories of errors that can come up here. 

1. User's account can't be found. This case would be pretty unusual.
2. Some sort of system problem that renders the service unreachable. 

We probably want to produce different error messages in the UI for each case.

**Comment by kevinreiss** [comment]
Decided to produce a single error message for both cases.
