### ISSUE TITLE
Add "Trace Item" link for available items?

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#162]
If an item is listed as "Available" but cannot be located in the stacks, a user needs a way to get to the item's Request page so they can place a Trace request on the item. @kevinreiss My understanding is that all patrons should be able to place a Trace Request.

(As a side note, the term "Trace" is seems problematic... probably should be "Report Missing" or something more meaningful to the end user, but that labeling may be something to look at in a usability study or A/B test, and to discuss with the Circulation department.)

**Comment by sdellis** [comment]
Actually, spoke with Joan about this and the strategy has been to make it intentionally hard to do (so the patron doesn't use it as a "paging" service). Not going to close it just yet because we may be able to address the concerns in a different way, but it should not hold up the Request app release in any way.

**Comment by kevinreiss** [comment]
I guess we should just suppress the "trace" message for on shelf items from the UI if we don't really want to deal with the current obfuscated workflow where things are intentionally hard to do.
