### ISSUE TITLE
Support Recall Requests

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#17]
This request should be made available as a last-chance fallback option for items that have an unavailable Voyager Item Status. This request will use Voyager's API since this request option is supported within the application. 

Voyager supports two recall options (both require a valid and active Voyager patron id):

https://developers.exlibrisgroup.com/voyager/apis/RESTfulWebServices/RecallPerTitle
https://developers.exlibrisgroup.com/voyager/apis/RESTfulWebServices/RecallPerItem

I believe the first one is the default to try and the second should be invoked only for multi-volume sets and serials.  We should make it clear in the presentation of this option that there are other preferable options available such as Borrow Direct or InterLibrary Loan.

**Comment by kevinreiss** [comment]
https://github.com/pulibrary/orangelight/blob/development/lib/orangelight/voyager_patron_client.rb contains methods implementing calls back to other portions of Voyager's account API. See how the code needed to make recalls happens fits in with that. Perhaps these should all be kept together a la Voyager Helpers in bibdata.

**Comment by kevinreiss** [comment]
Initially I'm think we should focus on the https://developers.exlibrisgroup.com/voyager/apis/RESTfulWebServices/RecallPerItem service. That can be tied directly to a given requestable object. This is the service we'd need for serial titles with enumerated item records and can also service monograph records since we have the barcode and ID of the items. The RecallPerTitle service seems liked it would only be used for a monograph record with a single or multiple copies of the same material. 

In terms of the required values for this query there are two that we didn't deal with for the ReCAP requests. The value ```voyager_ub_id``` in requests.yml is the ```patron_home_db```. The ```patron``` param is the numeric ```patron_id``` value that comes back in bibdata's patron http://bibdata.princeton.edu/staff/{netid} lookup response.

**Comment by kevinreiss** [comment]
Bib ID 2721756 is a recallable item we can use for initial testing.

**Comment by sdellis** [comment]
It seems that 2721756 does not exist in the local test data.  It looks like BibID 6890057 should work... or is there something about 2721756 that is special?

**Comment by tampakis** [comment]
6890057 should be fine. Additional records can be downloaded and added the test data too if need be:
```
https://bibdata.princeton.edu/bibliographic/2721756/solr
```

**Comment by sdellis** [comment]
Ok, thanks @tampakis...  it's better to have multiple test options.

**Comment by sdellis** [comment]
Ok, I imagine the following flow for the optimal experience:
1) User clicks **Request** on a "checked out" item.
2) On page load an ajax request is made to the Borrow Direct API and if it returns available items within a two (2) second period then notify the user and allow them to initiate the request
3) If no available items are returned or it times out, then offer the InterLibrary Loan option. (I'm a bit fuzzy on how this works... is there an API to determine availability at lending institutions? Can we use Illiad's [Lending Availability Service](http://rulekit.idsproject.org/LendingAvailabilityService.aspx)?)
4) If there's no way to determine availability via ILL, then offer two options, **Interlibrary Loan** (blue "primary" button) and **Recall** (standard grey button)

Does this make sense? If this is the case, should we stub out the Borrow Direct step for now?

**Comment by kevinreiss** [comment]
Yes, I like the idea of this workflow but I think we should tackle this in a separate issue once we have the underlying code in place to execute each of these operations (however we want to mash them up) independently.  

Unfortunately the "Lending Availability Service" isn't something a patron facing application can take advantage, it's not a "web" service but rather something buried in the ILLiad Client's workflow for staff to take advantage of.

**Comment by kevinreiss** [comment]
Bib 2721756 is an item that is actually charged to my account for the purposes of testing the recall request live. That way we don't recall a book someone actually wants.

**Comment by kevinreiss** [comment]
In any tests we stub out for recall requests the condition that makes an item eligible for recall is a Voyager item status that is termed to be "checked out" in the Blacklight UI. Requestable materials with item level records with a "missing" status are not eligible for recall. Requestable materials that have no item level details are not eligible for Recall. In practice only standard, circulating items should ever get into a status that will allow them to be "recalled". 

https://docs.google.com/spreadsheets/d/1HVQ7nJdX7AiK4J5BQIMTXnJDF4mKJEQbj3UmH0-VMsg/edit#gid=1320503261

**Comment by kevinreiss** [comment]
Closed in c8d6faf5caea42149621d9585d666d17fe80ee2e. Thanks @sdellis
