### ISSUE TITLE
Hide Enumeration Column

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#176]
When no enumeration is present on any requestable item attached to a record the column should be hidden in order to streamline the display. 

Ex: https://pulsearch-dev.princeton.edu/requests/9918797

**Comment by kevinreiss** [comment]
@sdellis what do you think of this one. In many cases it just seems like empty space.

**Comment by sdellis** [comment]
I agree it should not be there if there is no information to show. I wonder if it will have any impact on #190 ?

**Comment by kevinreiss** [comment]
Possibly, generally a record with multi-holdings would be enumerated at all locations, but I wouldn't be surprised if something broke that pattern.
