### ISSUE TITLE
ILL Volume Mapping Issue

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#177]
Our ILL links on journal items such as https://pulsearch-dev.princeton.edu/requests/2971301?mfhd=3286663&source=pulsearch take you to a form in ILLiad that is intended to service both monograph and whole journal requests. There aren't "volume" or "number" fields in that form. Only "edition" is currently present. We should either add those two fields so enumeration can be used when present or map them into the "edition" field. Given the nature of ILLiad we'll probably have to do the latter.

**Comment by sdellis** [comment]
Why can't we add those two fields?  I think there could be confusion when "Volume 2" shows up in the Edition field of that form.

**Comment by kevinreiss** [comment]
Discussed this issue with ILL staff. Liza and Peter will resolve this on their side.

**Comment by sdellis** [comment]
I worked with Liza and Paul today to map these values in Illiad and have resolved the issue. [Proof](https://lib-illiad.princeton.edu/illiad/illiad.dll?Action=10&Form=30&genre=book&isbn=9780874369281&rft.au=Charny,+Israel+W.&rft.pub=Santa+Barbara,+Calif:+ABC-CLIO&rft_id=42771674&sid=pulsearch.princeton.edu:generator&title=Encyclopedia+of+genocide+/&volume=Vol.1&issue=12).
