### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#187]
See https://pulsearch-dev.princeton.edu/requests/10140050?mfhd=9929804&source=pulsearch bombs out in current form code.

**Comment by sdellis** [comment]
This could be a data error. Bring up with Marie.

**Comment by kevinreiss** [comment]
@mzelesky let me know what you think needs to happen with this record, bib ID 10140050. Is this a scenario the form code should handle or should it be treated like an error?

**Comment by mzelesky** [comment]
There are many records like this, where the holding location is ReCAP, there is no call number, and there is no item. This record came in with a vendor record load. These records come in with provisional data, then catalogers finish processing the book at a later date. How are other such 'in-process' records handled for locations outside of ReCAP?

**Comment by kevinreiss** [comment]
https://bibdata.princeton.edu/availability?mfhd=9929804 provides no availability data. The "in process" items are able to return data in this call. The holding record 9929804 exists. @mzelesky @tampakis is this a bug in our code or bad data in Voyager?

**Comment by mzelesky** [comment]
This holding has no item and no order attached to it. This was a record I was supposed to delete on February 28th due to records loading on the incorrect fund. I somehow missed this one. Deleting now. Regardless, with no items attached to a mfhd, the get_full_mfhd_availability method in Voyager Helpers will return an empty set, right?

**Comment by tampakis** [comment]
Correct, the full mfhd availability method assumes that the mfhd has item records associated with it. Perhaps I should modify the record to provide availability info also when there aren't any item records?

**Comment by mzelesky** [comment]
Would it be enough for the response to say 'No item records are attached to record 9929804' instead of 'Record: 9929804 not found'?
