### ISSUE TITLE
Configurable Success Flash Message for a Request Submission

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#189]
Message confirmations displayed in the rails flash upon a successful submission for each request type should be configurable in request.en.yml. Right now we use the same one for all request types.

**Comment by sdellis** [comment]
How is this supposed to work for "On Order" or "In Processing" ReCAP items? I assume statuses should trump the request type when determining the message to relay to the user.

**Comment by kevinreiss** [comment]
On Order and In Process are "services" in this context, so they UI should present a confirmation that matches up with that status.
