### ISSUE TITLE
On Order enhancements

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#207]
The "Request" label for On Order items is misleading. Indicate that this can take a long time… should provide BD option as well as a way to indicate “interest” with a time frame. CC a selector on the "request" so they can follow up, rushing the order if necessary.

**Comment by kevinreiss** [comment]
We should see if borrow direct actually will allow a Princeton user to put a request for an "on order" title. I'm not sure if BD's polling returns that as a locally available copy. If that is the case users will be disallowed for submitting a BD request for the title in question.
