### ISSUE TITLE
Borrow Direct "fallback" Message Wording

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#210]
Our current wording when you get a prompt for a "fallback" borrow direct title/author search is 

```Good choice! Your best bet is Borrow Direct. Request this item via the BorrowDirect site. Checkout period is 12 weeks, with no renewals.```

This seems indicate it is likely the item is available. We should make this less conclusive. What about?

```
Good choice! Your best bet is Borrow Direct. See if a version of this item is available via the BorrowDirect site. Checkout period is 12 weeks, with no renewals.```

**Comment by sdellis** [comment]
I like this wording better. I think people were put off by the previous line's mention of "another edition may be available".
