### ISSUE TITLE
Handle ReCAP Records with No Item Records

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#23]
Need to display some sort of note for user: Example Bib ID 3861539.

**Comment by kevinreiss** [comment]
Another example:

Bib ID: 308 is actually stored with Bib ID: 626515 at ReCAP.

**Comment by kevinreiss** [comment]
Per Mark Z. we have over 17,000 ReCAP bibs with no items. We need to develop a general purpose approach towards handling this (fairly sizable) edge case.

**Comment by kevinreiss** [comment]
bib ID 3861539 still fails.

**Comment by kevinreiss** [comment]
@sdellis This is an extreme edge case related to #53. Need to review with Joan/Marie how this particular scenario needs to be handled.  Essentially this is a case where one bib ID (308) that has a recap holding has it's item level data attached to another bib ID (626515) at ReCAP.

**Comment by sdellis** [comment]
Ok, going to hold off until we hear from Joan/Marie. I assume that the scenario with bibID 626515 is different from the 17,000 ReCAP records that have no item info.  If so, perhaps we should open another issue.  I also don't know from this issue description whether 3861539 is part of the edge case described for bibID 626515.  If not, I will add bibID 626515 to the OrangLight local test data so we can move forward on this one.

**Comment by sdellis** [comment]
I assume this would be a "user supplied fill in" form?

**Comment by sdellis** [comment]
If it's a ReCAP holding with no barcode, bring "Location has" and "Location note" data into the form (make them part of the form submission)... allow for user supplied fill in and send in an email to Joan's people.

**Comment by sdellis** [comment]
Use these, and load into the test data: 

> Bib ID: 308 is actually stored with Bib ID: 626515 at ReCAP.

**Comment by kevinreiss** [comment]
Wait to solve this when SCSB system is in operation. There is no programatic way to deal with this record state in Voyager.

**Comment by sdellis** [comment]
This record has some weirdness that may be a separate issue: `requests/3861539?mfhd=4162824&source=pulsearch`

It's a record with no items with a ReCAP holding, however the requestable.services only include `on_shelf` and the submission.service_type value only includes `paging`.
