### ISSUE TITLE
Recap/SCSB Retrieval Request max out at 20 Items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#247]
No more than 20 barcodes can be submitted in a single RETRIEVAL request. Update Requests::Recap request service class to handle this limitation.

**Comment by sdellis** [comment]
EDD requests are the bigger problem here because they only currently allow one simultaneous request. Make sure both types of requests do a separate POST for each item. For performance reasons, perhaps bundle PRINT requests in batches of 20.

**Comment by carolyncole** [comment]
We are sending each item separately (https://github.com/pulibrary/requests/blob/main/app/models/requests/recap.rb#L22).  Closing this.
