### ISSUE TITLE
Recalls are set to expire immediately

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/requests#266]
Joan noticed that when a recall is placed via Blacklight, the recall is set to expire immediately. This results in the loan period being shortened for the person who has the book checked out, but the request is immediately cancelled for the patron that made the request.

**Comment by sdellis** [comment]
Thanks for the heads-up, @mzelesky. So, the one parameter I we are not sending Voyager's Recall API is `<last-interest-date>` because I was not sure what it meant or if we needed it. I imagine this might be related. The value of this param should be:

> The latest date in which the item must be supplied in yyyymmdd format

What does this mean, and what date should go there when someone makes a "recall" request?

**Comment by kevinreiss** [comment]
I assume that last-interest-date means how long the user is willing to wait for a Recall. We either need to provide the user with a date picker for them to pick that time period or just set a default value of say 3 months from today's date and advise the user as such when a recall is placed. @mzelesky or @sdellis I would check with Joan on which method is preferable. I'd lean towards the latter.

**Comment by mzelesky** [comment]
I laid those 2 options out to Joan, but I will confirm which one she wants. I was leaning towards the default value option, but in the old catalog, patrons were able to select a date. It sometimes led patrons to select '0' days which would lead to the same problem users are having in Blacklight. I'll post on this ticket when I get an answer back from Joan.

**Comment by mzelesky** [comment]
From Joan:

"I want to go with [a default value for not needed by] and have the expiration be 60 days or two months.  We do not need any explanation.  
If we hear that patrons are confused by some of the recall process, we’ll write up some text."
