### ISSUE TITLE
Make users aware of duplicate records that may be of interest

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#286]
If an item is unavailable, render the “other versions” links on the request form. These are stored in the solr document for the record. 

Users should be encouraged (in some way) to use these over BorrowDirect, ILL, or Recall (if available).

**Comment by jrgriffiniii** [comment]
This was given priority while working to resolve https://github.com/pulibrary/orangelight/issues/990#issuecomment-358328952

**Comment by kevinreiss** [comment]
Feature deprecated.
