### ISSUE TITLE
Location Code anxadoc

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#295]
The items stored under this location code need to emailed to an email address ```docstor@princeton.edu``` instead of a standard annex request destination.

**Comment by kevinreiss** [comment]
@sdellis another edge case for annex emails. Related to #296. This email isn't associated with a pickup location unfortunately. I wonder if we can get Marie to add and Joan to add one. Otherwise I guess some sort of helper method can be deployed for the mailer to override default behavior.

**Comment by sdellis** [comment]
Is there an example record we can use for testing?

**Comment by kevinreiss** [comment]
Advanced search allows you filter by holding location: https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=anxadoc&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search.
