### ISSUE TITLE
Redirect Upon a Successful Submission

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#31]
Provide a means to redirect the user back to the source page if they submit a successful request. This could be an automated redirect or a more passive option such as providing an explicit back link in the confirmation message.

**Comment by kevinreiss** [comment]
@sdellis Do you think this behavior as any merit. If no, please close this.

**Comment by sdellis** [comment]
We added the "back to record" link to the top. I think that is sufficient. I would advocate OL not opening a new tab/window for Requests, but that can be a separate issue in OL.
