### ISSUE TITLE
Broken ReCAP Record

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#310]
https://pulsearch.princeton.edu/catalog/10139326 has no item records and isn't "On Order" so the current request form is broken.

**Comment by kevinreiss** [comment]
somewhat related to #23 - still an ongoing issue with SCSB in place.

**Comment by sdellis** [comment]
Example record above no longer works. Use `requests/3861539?mfhd=4162824&source=pulsearch`
