### ISSUE TITLE
Form Contrast Issue

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#334]
https://pulsearch.princeton.edu/requests/1225885?mfhd=1402126&source=pulsearch. Blue on Blue is the issue. Also see https://pulsearch.princeton.edu/requests/1225885?mfhd=1402132&source=pulsearch. Red background, white text.

**Comment by sdellis** [comment]
I checked the "blue on blue" and foreground of #31708F and a background of #D9EDF7 and it complies with the WCAG 2.0 AA requirements according to the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/) with a 4.53:1 ratio. 

The link in the blue was not compliant. PR #356 fixes that and also fixes the white on red issue.
