### ISSUE TITLE
Make In Library Use / Supervised use More visible

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#337]
Example: https://pulsearch.princeton.edu/requests/SCSB-8024487?source=pulsearch.

Connect "In Library Use" with the print dialog option. Users miss it in the current location.

**Comment by kevinreiss** [comment]
related https://github.com/pulibrary/requests/issues/315.

**Comment by sdellis** [comment]
When the user selects the physical delivery option they should be made aware of the restriction in some fashion. 

In this particular case another unrestricted copy is available under a different bibid (SCSB, etc). https://pulsearch.princeton.edu/catalog/SCSB-8024487 
(See "Other Versions")

The user should be made aware of this unrestricted option before placing a request on an item with restrictions.

**Comment by kevinreiss** [comment]
The other versions block is generated by querying the solr index on the fly for matching ISBNs, ISSNs or OCLC numbers. If we could make the form aware of the results of that query we have to decide on how much info about the other versions we want to try and incorporate into the form. Do we just want to make them aware there might be something else and give them a clearly labeled link where they can look at the other form or do we want to try do something more sophisticated and actually tell them something about the status and restrictions/non-restrictions on items from the other form or even try and load the requestable items from the "other version" into the same form? The last option would require some fairly major re-factoring because their are some assumptions baked in about all items in the form sharing the same bib record.

**Comment by sdellis** [comment]
After thinking about this a bit more, I think the simplest and most effective approach is to go with a variation of the first option. However, I think that this notice should only show up if they are about to request a restricted item when there are circulating copies available. For example, if they are about to request the circulating copy, we should not alert them to copies that have restrictions.

If, after clarifying/emphasizing the label, users continue to request unwanted restricted items, perhaps we create a confirmation dialogue that pops up _only_ when requests are made to restricted items for which there are circulating copies. This dialogue would ensure they understand what they're doing and it's likely not what they want.
