### ISSUE TITLE
Missing net ID in Voyager Error Handling

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#34]
Should gracefully handle an exception raised when a CAS authenticated user doesn't have a net ID in the voyager database. In these instances form feedback should advise "visiting" fellows to contact circulation to make sure they have been registered with a net ID in the system.

**Comment by kevinreiss** [comment]
Hi, this one seems pretty straightforward. If you have any questions send me a message. This would be a scenario where one logs with CAS but doesn't actually have a barcode in the system. Happens occasionally.

**Comment by sdellis** [comment]
Ok, so they have all normal CAS privileges and we just need to display a "info notice"? Or are they not able to use certain services until they get a barcode?

**Comment by sdellis** [comment]
User should not be able to proceed without going through Circulation (call/email/in person).
