### ISSUE TITLE
Handle "empty" online holdings

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#341]
See https://github.com/pulibrary/orangelight/issues/1020. Current example: https://pulsearch.princeton.edu/requests/5409973?mfhd=5565656&source=pulsearch

**Comment by christinach** [comment]
https://app.honeybadger.io/projects/54399/faults/35790005#notice-summary

**Comment by tampakis** [comment]
https://catalog.princeton.edu/requests/4961486
