### ISSUE TITLE
Load and cache delivery locations with a service object instead of a constant

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#342]
The requests_initializer sets a global DELIVERY_LOCATIONS constant. Refactor this to come for the Requests.config object. 

See https://github.com/pulibrary/orangelight/pull/1033 for a solution for a different global constant.

**Comment by hackmastera** [comment]
I'm working on refactoring the holding_locations referenced above. Setting these in initializers keeps us from being able to effectively mock and stub external api calls in our tests. I'm going to work on the same sort of refactor for delivery_locations in OL; will make sure to keep/deprecate the current constant so this repo can be updated to use the new class method.
