### ISSUE TITLE
In Process Sax and Rccpz Items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#357]
When items in these two locations have an item record with the "In Process" status they should pass the status information to Aeon via the notes field.

**Comment by kevinreiss** [comment]
Current example: https://catalog.princeton.edu/catalog/9666334. These treatment should be given to in process items in the "sax" and "rcppz" location codes.

**Comment by sdellis** [comment]
I don't see a "notes" field. There are `iteminfo` fields, 1-5. Would the status information be passed through one of those fields? 

Also, when you say status information, do you mean all of the status information, or just the "In Process" label? In this case there's an array that could be concatenated into a list of statuses: 
```
"status": [
 "Not Charged",
 "In Process"
]
```

**Comment by sdellis** [comment]
Conversation with Kevin: use `notes` field as per the Aeon OpenURL syntax. Only pass "In Process" status through to Aeon.
