### ISSUE TITLE
Where to Find it Links go nowhere

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#361]
See https://pulsearch.princeton.edu/requests/563041?id=563041&loc=gestpe. Need to be updated to new endpoint used on the "record" page.

**Comment by sdellis** [comment]
So the endpoint generated on the "record" page is created with this service: https://github.com/pulibrary/orangelight/blob/master/app/services/stackmap_service.rb

Is there a way we can use that service in the Requests engine without copying it and remembering to make changes in both places?

**Comment by kevinreiss** [comment]
We don't show these any longer in the form.
