### ISSUE TITLE
Enable "paging" for main ppl location

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#362]
Items with an "Available" status located in the "ppl" location code should be "pageable" in the fashion Annex items are. The paging email destination should be "ppllib@princeton.edu". Enable this should be similar to what was done for the "pres" location. We'll need to have the new email template signed off by Willow and the PPL location manager.

**Comment by sdellis** [comment]
@kevinreiss should the delivery location be restricted on PPL paging requests?
