### ISSUE TITLE
Borrow Direct Fallback Query Needs to escape the "+" character

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#392]
Current example

 https://catalog.princeton.edu/requests/3469583?mfhd=3796877&source=pulsearch

Current syntax passed over (generated by the "GenerateQuery" class in the borrow_direct gem is:

https://catalog.princeton.edu/borrow-direct?query=ti%3D%22forming+the+academic+profession+in+east+asia%22+and+au%3D%22kim%22

That needs to be:

https://catalog.princeton.edu/borrow-direct?query=ti%3D%22forming%20the%20academic%20profession%20in%20east%20asia%22%20and%20au%3D%22kim%22

**Comment by carolyncole** [comment]
No longer using this functionality for borrow direct.
