### ISSUE TITLE
Catch scsb parse errors and set empty hash

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/requests#393]
from honeybadger error https://app.honeybadger.io/projects/54399/faults/41321815

looks like there's a service down condition that doesn't return a status code.

we should catch parse errors here https://github.com/pulibrary/requests/blob/0a249234d91849810069ee9075d889e10c0a93d9/app/models/concerns/requests/scsb.rb#L53 and set to an empty hash, as in the false branch of this ternary.

**Comment by kevinreiss** [comment]
Yes, unfortunately when there is some sort of general service failure the server just sends back a 200 with just a string of error text instead a status.
