### ISSUE TITLE
Bibs without enumeration in items should only allow title-level recall

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/requests#394]
If none of the items attached to a particular bibliographic record contain enum/chron information, only a title-level recall should be possible. In this case, specific locations should not be visible to the user; only a single request row. The ILS will determine which item is recalled. For bibs with any enum/chron, the request functionality should remain the same.

**Comment by kevinreiss** [comment]
Revisit this after the Alma go live. Alma has better title request functionality than Voyager.
