### ISSUE TITLE
Change Fine Annex B Email Destination

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#422]
Requests for items at locations attached to Fine Hall (Annex B) should now send email to the Forrestal Annex A email address. Fine Hall email being deprecated due to engineering library move to lewis.

**Comment by tampakis** [comment]
https://github.com/pulibrary/requests/blob/0aed6806eccd09a738c2e43eb4f57215b4c5d98c/app/views/requests/request_mailer/annexb_email.text.erb

**Comment by kevinreiss** [comment]
Former fine hall locations have been reassigned to annexa in bibdata. Perhaps we should just delete this template since annexb isn't coming back. Confirm with Marie C.
