### ISSUE TITLE
The item displays a 'not available' status in the request form even though it is 'available'

### ISSUE THREAD

**Issue by christinach** [pulibrary/requests#433]
https://catalog.princeton.edu/requests/4981710?mfhd=5177610&source=pulsearch

**Comment by christinach** [comment]
![Screen Shot 2020-01-06 at 10 13 41 AM](https://user-images.githubusercontent.com/9905193/71826979-3e1edd00-306d-11ea-85e7-245a01626e9e.png)

**Comment by carolyncole** [comment]
Should have been fixed using bibdata statuses
