### ISSUE TITLE
Disable ReCAP Physical Processing Requests

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#439]
I think we should out comment the option: https://github.com/pulibrary/requests/blob/master/app/models/requests/router.rb#L98. We didn't make physical delivery a configurable option for the system as we did EDD. EDD requests should remain as is. Probably should also comment this fallback option which facilities physical requests for the few recap records that have item records: https://github.com/pulibrary/requests/blob/master/app/models/requests/router.rb#L98.

**Comment by tampakis** [comment]
Add a notice in the form hat ReCAP items are not physically requestable
