### ISSUE TITLE
Display of request "services" available for "charged" items

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#44]
When an item-level record has a "Charged Status" it can potentially be serviced by one of three request options at the library, Borrow Direct, Interlibrary Loan, or Recall. The proposed optimal workflow would be:

1) User clicks **Request** on a "checked out" item on the Item Show page.
2) On page load, an ajax request is made to the Borrow Direct API and if it returns available items within a two (2) second period then notify the user and allow them to initiate the request
3) Option A: If no available items are returned or it times out, then offer the InterLibrary Loan option. (I'm a bit fuzzy on how this works... is there an API to determine availability at lending institutions? Can we use Illiad's [Lending Availability Service](http://rulekit.idsproject.org/LendingAvailabilityService.aspx)?)
Option B: If there's no way to determine availability via ILL, then offer two options, **Request via Interlibrary Loan** (blue "primary" button) and **Recall** (standard grey button) and show turnaround times to further dissuade a Recall

Some further constraints to consider:

1. Only "cas" authenticated users are eligible to utilize borrow direct. Barcode-only or "Access" patrons cannot.
2. The Recall option is not available for items with an item status that falls under "Missing". Recalls should also be rejected for Patrons that have borrowing blocks. We need to decide if we want to reject these before they are submitted or allow voyager to reject them and process the result. 
3. Option A proposed under ILL isn't currently feasible for a patron facing application given the current implementation of the ```Lending Availability Service``` within the ILLiad staff client. Will confirm with other Library staff. 
4. Borrow direct "matches" can generally fall into two categories. An "exact" match that utilizes a standard number like an ISBN or LCCN number. Or a "fuzzy" match that utilizes title and author. We can tell if a record can be an "exact" or "fuzzy" match from bibliographic metadata, only "exact" matches should be handled in the fashion proposed in step one of the optimal workflow.

**Comment by kevinreiss** [comment]
Try and execute Borrow Direct and ILLiad Lookups via Umlaut's Jquery Content Utility API, https://github.com/team-umlaut/umlaut/wiki/JQuery-Content-Utility. Service keys are "borrow_direct" and "document_delivery". The borrow direct service be expected deal with the question of "exact" and "fuzzy" logic, however we will need to examine the record format and item count because we do not want to call borrow direct when an unavailable item is part of a serial or a multi-volume set.

**Comment by kevinreiss** [comment]
I discussed borrow direct's utility for multi-volume sets and serials with our staff for that office and they indicated that for journals or multi-volume sets that have more than a single item record at a holding and are enumerated there is no point in giving the user the opportunity to try Borrow Direct for these. In these cases it would be better to send the user to ILL via an OpenURL with as much metadata as we can.

**Comment by kevinreiss** [comment]
Keeping open until we get staff feedback on this.

**Comment by kevinreiss** [comment]
@sdellis would you mind taking a look at some examples of charged items here and make sure they work out accordingly. This has been re-factored a lot and I want to make sure it works as expected before we present it to staff. Thanks. Please note bib IDs that are good examples (both pro and con) in this issue.

**Comment by sdellis** [comment]
@kevinreiss I looked at the examples we have and they are working as expected.  I will see if I can track down some others in prod and add them to the test data. 

As for checking with regard to Barcode-only and Access users, I noticed that there is a factory for testing for these. Does [this block](https://github.com/pulibrary/requests/blob/development/spec/factories/requests/users.rb#L17-L20) cover both Barcode-only and Access users, as neither have a NetID, or just "access" as the variable seems to indicate?

**Comment by sdellis** [comment]
I don't know what a "borrowing block" is supposed to look like on a patron's record.  We should add this to the User factory so we can test and make sure Recall isn't an option (like we do [here](https://github.com/pulibrary/requests/blob/development/spec/models/requests/requestable_spec.rb#L214-L216) for "Missing Items")

**Comment by sdellis** [comment]
I am also having trouble figuring out how to log in as an "Access" user, which might help me figure out some of the questions in the above comment.  I'm not sure what the intended behavior is for the "Other Users" in the Requests app, but there is no button for submission and a carriage return does not submit the form either.  (FYI - If I try to log in via OrangeLight, it expects a 14-digit barcode, as I imagine my last name may not be matched to an "access" user.)

**Comment by kevinreiss** [comment]
Access users can't actually login. Ideally we'd treat the "guest user" initiated when you visit Orangelight anonymously as the "access user". I think maybe hold off on working on trying to flesh out how examining the type of user impacts the request form behavior until we review this further.

**Comment by kevinreiss** [comment]
```valid_access_patron``` probably dates from the time I thought ```barcode``` and ```access``` patrons were the same thing. In reality we'd need to mock three users.

1. cas
2. barcode
3. access

**Comment by sdellis** [comment]
Ok, sounds good.  Just to be clear, I'm not able to use this form to login via barcode either.

![screen shot 2017-01-25 at 9 55 31 am](https://cloud.githubusercontent.com/assets/609368/22295290/6f1e4ad2-e2e4-11e6-9ff7-b5aca1d22653.png)

**Comment by kevinreiss** [comment]
Yes, it has never been connecting to the routine that used in the standard Orangelight user sign_in page.  We should rectify that at some point in #43.
