### ISSUE TITLE
Enable a scanning option for all items in the catalog that are in circulating and non-circulating locations 

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#440]
Connect through to Iliad and fill in the form automatically so that the form is automatically filled in and then make the user click the button.

**Comment by carolyncole** [comment]
An example of a item that you can see is for a checked out item: see the OPENURL . Change form=20 from form=30 and add value=GenericRequestArticleRequest; Change ISBN to ISSN; change title to PhototJournalTitle;

**Comment by tampakis** [comment]
Example Url Before: https://lib-illiad.princeton.edu/illiad/illiad.dll?Action=10&Form=30&genre=book&isbn=9781493996971&rft.au=Apte%2C+Suneel+S.&rft.date=2020&rft.pub=New+York%2C+NY%3A+Humana+Press&rft_id=1121104200&sid=catalog.princeton.edu%3Agenerator&title=ADAMTS+proteases+%3A+methods+and+protocols
Example Url After: https://lib-illiad.princeton.edu/illiad/illiad.dll?Action=10&Form=20&value=GenericRequestArticleRequest&genre=book&issn=9781493996971&PhotoArticleAuthor=Apte%2C+Suneel+S.&PhotoJournalYear=2020&rft.pub=New+York%2C+NY%3A+Humana+Press&Notes=1121104200&sid=catalog.princeton.edu%3Agenerator&PhotoJournalTitle=ADAMTS+proteases+%3A+methods+and+protocols&PhotoArticleTitle=All&PhotoJournalInclusivePages=All

**Comment by carolyncole** [comment]
Add a form to Iliad that is called `Book Scan Request`

**Comment by tampakis** [comment]
Use existing form for `genre=journal`

**Comment by tampakis** [comment]
https://catalog.princeton.edu/requests/9709739?mfhd=9531676&source=pulsearch
