### ISSUE TITLE
Add Submission tests for multiple request types 

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#48]
See #17

**Comment by sdellis** [comment]
This should also cover a scenario when one request is successful, but another is not.

**Comment by sdellis** [comment]
@kevinreiss Are there any situations in which a Recall request cannot be made or returns an error after the pickup location lookup returns successful? As I understand it, this does a check to make sure it's "recallable" and if it's not, the user will not be able to submit the form with it checked. If that's the case we only need to create tests for multiple successful request types, correct?

**Comment by kevinreiss** [comment]
I don't know. We'd have try to the use system with an account that has a block on it to see if the pickup list call still works. My thinking would that it would fail. I don't know for sure.
