### ISSUE TITLE
Staff Pickup Locations Sort

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#50]
When present place these at the bottom of select lists.

**Comment by sdellis** [comment]
How do we know which ones are staff pickup locations?

**Comment by kevinreiss** [comment]
There is staff flag in the delivery_location model.

**Comment by sdellis** [comment]
Should the labels indicate that they are "staff only"?

**Comment by kevinreiss** [comment]
Yes, probably.

**Comment by kevinreiss** [comment]
We need to make sure this call only happens once for a given "holding" in a request. Otherwise it's repetitive.

**Comment by kevinreiss** [comment]
Closing.
