### ISSUE TITLE
"sid" param in ILLiad Open URL should include bib and holdings ID values

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#506]
This will allow staff to easily look up the record if needed. This param is mapped into the "CitedIn" field in the illiad form. It current comes through looking like this:

```catalog.princeton.edu:generator```

So the staff can click through the record page for the item in question it would be good to make this specific to the record.

```catalog.princeton.edu/record/{bibid}```

https://github.com/pulibrary/requests/blob/09974084d075e6ecbd3ea8a2cb3c92cb712055ea/app/models/concerns/requests/illiad.rb#L68

**Comment by carolyncole** [comment]
closed by https://github.com/pulibrary/requests/pull/511
