### ISSUE TITLE
Confirm title length for open url

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#517]
Check to see if the titles that are longer than 256 go through

https://catalog.princeton.edu/catalog/896119

**Comment by carolyncole** [comment]
@kevinreiss It does get cut off, but does not break:
![Screen Shot 2020-04-08 at 9 24 18 AM](https://user-images.githubusercontent.com/1599081/78789199-cc5f7380-797a-11ea-8825-5c0abc67555a.png)

**Comment by kevinreiss** [comment]
👍
