### ISSUE TITLE
Is code related to the "thesis" holding location required any longer?

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#528]
There are few methods in the codebase that apply special behaviors and test for conditions for the holding location "thesis". I actually think this location may no longer be used. In the production catalog zero items currently are assigned to this location. I think this may be an artifact of an earlier normalization routine for senior thesis content drawn from dspace which have all now been moved to general mudd location codes. @christinach is this accurate?

**Comment by christinach** [comment]
@kevinreiss @mzelesky and I looked into this: looking in the catalog https://catalog.princeton.edu/?f%5Baccess_facet%5D%5B%5D=In+the+Library&q=id%3Adsp*&search_field=all_fields all of the items with an id dsp (dspace) are in the Mudd Library and location_code is "mudd" https://catalog.princeton.edu/catalog/dsp019c67wp402/raw.  As a first answer I would say that checking location mud is enough to decide for the request. 
But there is a dspace:true or dspace:false in the holdings_1display key "thesis" which seems to change the availability.
Based on this example https://catalog.princeton.edu/catalog/dsp01k0698b34p we should check the key thesis and the dspace value and if it is false (which means that it's embargoed), then we should not display the Reading room Request button. Is this correct? this is the holdings_1display field: `"holdings_1display":"{\"thesis\":{\"location\":\"Mudd Manuscript Library\",\"library\":\"Mudd Manuscript Library\",\"location_code\":\"mudd\",\"call_number\":\"AC102\",\"call_number_browse\":\"AC102\",\"dspace\":false}}"`

**Comment by christinach** [comment]
What do you mean by 'catalog zero items'?

**Comment by christinach** [comment]
we are still using this feature and embargoed records have the attribute dspace:false . We need to update the requests chart with this info.
