### ISSUE TITLE
Handle Records with No Item-level data

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#53]
Example: 

Nil error in stacktrace due to missing item ID: http://pulsearch1.princeton.edu/requests/4492846
See old system: http://library.princeton.edu/requests/4492846

We should see one requestable item with an optional fill in row where the user can self-supply a volume.

**Comment by kevinreiss** [comment]
@sdellis could you look at this one and make see if the form handles the case of an item with no item records attached to a holding properly. 

1.

**Comment by sdellis** [comment]
This should have been referenced in the current PR, but for some reason wasn't.

**Comment by kevinreiss** [comment]
Additional volume information should be optional in no item item records. Currently you can't submit the form unless you fill something in. 

http://pulsearch1.princeton.edu/requests/4492846
