### ISSUE TITLE
Coins requests should redirect to form for contacting Alan Stahl

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/requests#541]
From Numismatics sprint wrap-up meeting. 5/19/2020.

Coins cannot be viewed in the reading room. They can only be viewed by appointment with the curator and people should contact Alan directly. “For an appointment to see coins contact Alan Stahl, curator of numismatics”

**Comment by carolyncole** [comment]
@eliotjordan do you know if this is still something folks want?  Using AEON seems like a better approach, since statistics can be more easily gathered from the system.  We could possibly create a queue for him in AEON.

**Comment by eliotjordan** [comment]
@carolyncole That seems reasonable.

**Comment by carolyncole** [comment]
Contact SarahL slogue@princeton.edu to set up a rule in AOEN for a special Queue

**Comment by kevinreiss** [comment]
Spoke with Sara, we are going to close this and revisit this question again later if it comes up.
