### ISSUE TITLE
Revised Email Confirmation Text for Paging Email

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#543]
Emails should be formatted as print-friendly HTML. The patron's last name, hold expiration date (currently 7 days from the current date) should be displayed clearly and be the focus of the display. 

- [x] Enable HTML formatting in email notifications
- [x] Ensure emails are printer friendly
- [x] Make the user last name the first item displayed in the email to staff
- [x] Make sure the hold expiration date is displayed in the email text
- [x] Obtain updated message text sent to patron from digitization/request task force.
- [x] Confirm both patron and circulation department are getting an email - right seems only circ is getting one in manual testing

**Comment by escowles** [comment]
I confirmed with Barbara that a website giving guidance on social distancing/PPE procedures is forthcoming (expected Friday). A prominent link to this site should be included in the emails to patrons.

**Comment by escowles** [comment]
Latest text is:
>We appreciate your help in our efforts to slow the spread of Covid-19. When picking up and/or dropping off your books, please do so promptly, remain only in the designated pick-up area, wear a mask or face covering, and follow social distancing guidelines. Additionally, we appreciate your efforts to limit your number of trips to the Library.
>
>Sincere thanks.

**Comment by axamei** [comment]
@escowles do we have the link to the page about social distancing/ppe procedures?

**Comment by escowles** [comment]
@axamei It's https://library.princeton.edu/news/general/2020-05-27/pul-social-protocols
