### ISSUE TITLE
Re-Activate Paging Functionality In COVID-19 Branch

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#546]
Will likely need to review and update holding_location configurations in bibdata. https://github.com/pulibrary/requests/tree/COVID-19-CHERRY2

Past work in marc liberation to configure these features: https://github.com/pulibrary/marc_liberation/issues/603#issuecomment-600040048

**Comment by christinach** [comment]
- Locations which include the word 'Reference': 
`Locations::HoldingLocation.where(requestable:true).where('"label" LIKE ?', "%Reference%" )`
- Locations which do not include the Reference and most likely we want to update to be requestable: false (`count # 37`)
`Locations::HoldingLocation.where(requestable:true).where('"label" NOT LIKE ?', "%Reference%" )` (`count # 283`)

**Comment by christinach** [comment]
The circulates seem to be configured correct. We should consider the circulates: true locations for this change.

**Comment by kevinreiss** [comment]
Any location that is flag as circulates: false should be eligible to use this service.
