### ISSUE TITLE
Implement Voyager Hold Request 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#547]
Use this Voyager endpoint for holding records with barcoded items attached to them. The hold API will allow one to select any circulation desk for delivery by default, for this implementation we will need to restrict the physical delivery option, items can only be delivered to the circulation desk of the library the item is located at. 

- [x] Implement Hold Request at the Item Level for records with Items #571 
~~-[] Implement Hold Request at the Title Level for records without items #549 ~~
- [x] Implement a check to ensure non-circulating locations in campus libraries are not pageable (bibdata circulates: false flag for holding_locations) #569

**Comment by kevinreiss** [comment]
API Docs: https://developers.exlibrisgroup.com/voyager/apis/restfulwebservices/recallperitem/. 

GET: https://webvoyage.princeton.edu:7014/vxws/record/11451836/items/8183358/hold?patron={user[:patron_id]}&patron_homedb={db_identifier}&patron_group={user[:patron_group]}

```
<?xml version="1.0" encoding="UTF-8"?>
<response>
    <reply-text>ok</reply-text>
    <reply-code>0</reply-code>
    <hold allowed="Y">
        <pickup-locations usage="Mandatory">
            <pickup-location code="299" default="Y">.Firestone Library Circulation Desk</pickup-location>
            <pickup-location code="533" default="N">693 TSD Circulation Desk</pickup-location>
            <pickup-location code="356" default="N">Architecture Library Circulation Desk</pickup-location>
            <pickup-location code="333" default="N">Donald E. Stokes Library, Wallace Hall, Circulation Desk</pickup-location>
            <pickup-location code="303" default="N">East Asian Library Circulation Desk</pickup-location>
            <pickup-location code="345" default="N">Engineering Library Circulation Desk</pickup-location>
            <pickup-location code="440" default="N">Firestone Microforms Services</pickup-location>
            <pickup-location code="293" default="N">Annex A Circulation Desk</pickup-location>
            <pickup-location code="395" default="N">Interlibrary Services Circulation Desk</pickup-location>
            <pickup-location code="489" default="N">Lewis Library Circulation Desk</pickup-location>
            <pickup-location code="321" default="N">Marquand Library Circulation Desk</pickup-location>
            <pickup-location code="309" default="N">Mendel Music Library Circulation Desk</pickup-location>
            <pickup-location code="312" default="N">Harold P. Furth Plasma Physics Library Circulation Desk</pickup-location>
            <pickup-location code="400" default="N">Pre-Bindery Circulation Desk</pickup-location>
            <pickup-location code="394" default="N">Preservation Office Circulation</pickup-location>
            <pickup-location code="427" default="N">RECAP Circulation</pickup-location>
            <pickup-location code="315" default="N">Rare Books and Special Collections Circulation Desk</pickup-location>
            <pickup-location code="306" default="N">Seeley G. Mudd Library Circulation Desk</pickup-location>
            <pickup-location code="353" default="N">Technical Services Circulation</pickup-location>
            <pickup-location code="359" default="N">Video Collection: Video Circulation Desk</pickup-location>
            <pickup-location code="544" default="N">ReCAP Shared Collection</pickup-location>
            <pickup-location code="437" default="N">Borrow Direct Service. Princeton University Library</pickup-location>
            <pickup-location code="439" default="N">zDatabase Maintenance</pickup-location>
        </pickup-locations>
        <dbkey code="1@PRINCETONDB20050302104001" usage="Mandatory">Local Database</dbkey>
        <instructions usage="read-only">
            <![CDATA[<html><head><title>Hold Request</title></head><body>
You have chosen to place a <b>Hold</b> rather than a<b>Recall</b>.<p>This means that the item you selected will be available for you when 
the user who currently has the item checkeded out returns it.<br> 
This may be up to a year.
<p>
If you need the item sooner, please place a <b>Recall</b> instead of a Hold.</u><p><i>If you have questions, please contact any library
circulation desk.</i></body>
</html>
]]>
</instructions>
<last-interest-date usage="Mandatory">2020-06-26</last-interest-date>
<comment max_len="100" usage="Optional"/>
</hold>
</response>
```
Then PUT the same URL with this XML body. 

```<hold-request-parameters>
   <pickup-location>299</pickup-location>
   <last-interest-date>20200726</last-interest-date>
   <comment>testing hold request</comment>
   <dbkey>1@PRINCETONDB20050302104001</dbkey>
</hold-request-parameters>
```

**Comment by mzelesky** [comment]
There are non-circulating items within circulating locations. Example:

bib ID: 257717
item ID: 282630

If you perform a GET request for the item info via vxws:

`https://webvoyage.princeton.edu:7014/vxws/item/282630`

you get the following XML document:

`<?xml version=\"1.0\" encoding=\"UTF-8\"?><response><reply-text>ok</reply-text><reply-code>0</reply-code><item><itemData id=\"46\" name=\"permLocation\" code=\"f\">Firestone Library (F)</itemData><itemData id=\"0\" name=\"tempLocation\"/><itemData id=\"46\" name=\"location\" code=\"f\">Firestone Library (F)</itemData><itemData name=\"callNumber\">JK3401 .E462</itemData><itemData name=\"copy\">c. 1</itemData><itemData name=\"itemBarcode\">32101033513878</itemData><itemData name=\"enumeration\">vol.20(inc.)</itemData><itemData name=\"chron\">1994</itemData><itemData name=\"year\"/><itemData name=\"caption\"/><itemData name=\"freeText\"/><itemData name=\"typeCode\">2</itemData><itemData name=\"typeDesc\">NoCirc</itemData><itemData name=\"tempType\">0</itemData><itemData name=\"tempDesc\"/><itemData name=\"mediaType\">0</itemData><itemData name=\"mediadesc\"/><itemData name=\"itemStatus\">vol.20(inc.) 1994  Requests: 1</itemData><itemData name=\"itemStatusCode\">6</itemData><itemData name=\"itemDueDate\"/><itemData name=\"itemStatusDate\">2020-05-27 13:24:40</itemData><itemData name=\"todayDate\">2020-05-27 13:27:18</itemData><itemData name=\"pieceCount\">1</itemData><itemData name=\"amount\">0.00</itemData><itemData name=\"spineLabel\"/><itemData name=\"historicalCharges\">0</itemData><itemData name=\"historicalBrowses\">0</itemData><itemData name=\"historicalBookings\">0</itemData><itemData name=\"recallsPlaced\">0</itemData><itemData name=\"holdsPlaced\">1</itemData><itemData name=\"itemNote\">0</itemData><itemData name=\"reserveCharges\">0</itemData><itemData name=\"onReserve\">N</itemData><itemData name=\"shortLoanChgs\">0</itemData><itemData name=\"createDate\">2000-06-13</itemData><itemData name=\"createOperId\"/><itemData name=\"createLocation\"/><itemData name=\"modifyDate\"/><itemData name=\"modifyOperId\"/><itemData name=\"modifyLocation\"/><itemData name=\"lastTrans\"/><itemData name=\"clusterId\">1</itemData><itemData name=\"bibId\">257717</itemData><itemData name=\"libraryId\">1</itemData><itemData name=\"historicalReserveCharges\">0</itemData><itemData name=\"holdLocation\"/><itemData name=\"patronGroupCode\"/><itemData name=\"lastName\"/><itemData name=\"firstName\"/></item></response>`

The important thing to note here is `<itemData name=\"typeDesc\">NoCirc</itemData>`

If the item type is a non-circulating item type, the request should not be allowed.

Here are the non-circulating item types. This should be a definitive list. The types are case-sensitive.

`NoCirc
Closed
Res-No`

**Comment by kevinreiss** [comment]
@mzelesky is there any call in bibdata that would also expose this information?

**Comment by kevinreiss** [comment]
Doesn't appear to be at the moment. Would it be challenging to add it to https://bibdata.princeton.edu/items/282630.
