### ISSUE TITLE
Items in the Forrestal Annex do not submit

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#563]
![Screen Shot 2020-05-27 at 4 41 02 PM](https://user-images.githubusercontent.com/1599081/83070049-ddeb0080-a038-11ea-83a5-7f6cc312054a.png)

**Comment by kevinreiss** [comment]
Lewis library has the same issue

https://catalog-staging.princeton.edu/requests/581193?mfhd=634966&source=pulsearch

**Comment by kevinreiss** [comment]
Plasma Physics as well: https://catalog-staging.princeton.edu/requests/578830?mfhd=632337&source=pulsearch
