### ISSUE TITLE
Implement Hold Request at the Item Level for records with Items

### ISSUE THREAD

**Issue by christinach** [pulibrary/requests#571]

**Comment by kevinreiss** [comment]
The current related code that talks the voyager recall api endpoint is in https://github.com/pulibrary/requests/blob/master/app/models/concerns/requests/voyager.rb
1:13
the "service" class that manages making the requests to the api and managing any errors is https://github.com/pulibrary/requests/blob/master/app/models/requests/recall.rb
1:14
I think we have to implement a "on_shelf.rb" version of this to do the GET and PUT associated with the hold api

**Comment by kevinreiss** [comment]
I think we can build upon this and and add a "process_on_shelf" method to this class https://github.com/pulibrary/requests/blob/master/app/models/requests/submission.rb to manage the call and response of the service class.
1:18
For specs I did some mocking of the api calls to the recall: https://github.com/pulibrary/requests/blob/master/spec/models/requests/recall_spec.rb
For the hold API itself the GET is probably necessary to confirm the item is available for hold. The XML response has an element with an allowed attribute that we can look at. ```<hold allowed="Y">```

And then we can construct the PUT request and confirm the hold was successfully placed.

When a hold goes through successfully it shows up on the Blacklight /account page and can be cancelled by the user if they want.
