### ISSUE TITLE
Include Granular Enumeration for Serials in OpenURLs

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#58]
When forming requests for ILL, volume, issue, and date should be properly enumerated. Right now the mfhd availability response we use collapses 'enum' and 'chron' into a single value. We should either switch to the bibdata /item route for the full info or do away with the collapse in the mfhd availability call. 

https://bibdata.princeton.edu/availability?mfhd=9880418

vs. 

https://bibdata.princeton.edu/holdings/9880418/items

**Comment by kevinreiss** [comment]
@tampakis Thoughts on this. Would it be better just to use the full item lookup for any "request" related activities. Switching over to that is a fairly simple process.

**Comment by tampakis** [comment]
I think it would be easy to add the enum and chron as separate values into the availability service

**Comment by kevinreiss** [comment]
Should I open ticket in marc liberation to split these up?

**Comment by tampakis** [comment]
Voyager helpers please

**Comment by kevinreiss** [comment]
When https://github.com/pulibrary/voyager_helpers/commit/aa3dd3568ed167ee45b5283196539140f6443c79 is deployed to the production marc liberation environment update the code in this gem to handle this new granularity.

**Comment by kevinreiss** [comment]
This in production now. See https://bibdata.princeton.edu/availability?mfhd=977105 for an example. We need to adjust code that deals with enumerated values according.

**Comment by kevinreiss** [comment]
I think the following request types handle enumerated values in some fashion.

1. ILL
2. Aeon
3. Borrow Direct (doesn't pass them over but whether or not an item is enumerated determines it's eligibility for the service).

**Comment by sdellis** [comment]
It doesn't seem like OpenURL has a `chron` param, so I'm not sure where the `chron` data gets mapped to or if it should be passed along at all. It would be helpful to have some items with issue data too (unless chron is basically synonymous with issue?).

For example, I don't know if the enum values are `volume` or `issue` in this one:
requests/561774?mfhd=4736735

**Comment by kevinreiss** [comment]
I think this is the mapping:

enum=volume
chron=issue

When we display the values for end users I think enum_display is what we to show.
