### ISSUE TITLE
Some journals work, some do not...

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#584]
Working
https://catalog-staging.princeton.edu/requests/9642509?mfhd=9476185&source=pulsearch

Not Working
https://catalog-staging.princeton.edu/requests/10363208?mfhd=10362896&source=pulsearch

**Comment by kevinreiss** [comment]
The second has no items attached and seems to be at a holding at lewis. This looks like a potential cataloging issue.

**Comment by mzelesky** [comment]
I'll take a look and see if anything looks off.

**Comment by kevinreiss** [comment]
@mzelesky let us know what you think we should do with this edge case.

**Comment by mzelesky** [comment]
I have checked and double-checked the Lewis circulation policy, and restarted vxws multiple times. I don't know why this location (sciss) doesn't respond the same way as Firestone periodicals. But it's making me think locations connected to periodicals shouldn't be eligible for paging. More often than not, the material could be scanned if it's a periodical. And also, I don't know how many bound periodicals actually circulate.

**Comment by kevinreiss** [comment]
These will be eligible for scan on demand requests. There is something particularly weird about this record since our fallback options for holdings with no item records.
