### ISSUE TITLE
URLS that create a bad request

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#593]
https://catalog-staging.princeton.edu/requests/11395328?mfhd=11089235&source=pulsearch

https://catalog-staging.princeton.edu/requests/7617477

**Comment by carolyncole** [comment]
This item is not available to create a hold via voyager: https://catalog-staging.princeton.edu/requests/7617477

**Comment by carolyncole** [comment]
Both of the above issues had something a bit off in their holding information in voyager.  I've added better handling of errors in a PR to help with this, but these will not work until voyager is modified.  If someone requests then an email will got to `recapproblems@princeton.edu`

**Comment by mzelesky** [comment]
https://catalog-staging.princeton.edu/requests/7617477

This one is for an ebook on an iPad.

https://catalog-staging.princeton.edu/requests/11395328?mfhd=11089235&source=pulsearch
Unsure of what the issue could be here. I'm noting that there are current issues attached to the holding. I don't know if that could have any impact.

**Comment by kevinreiss** [comment]
@mzelesky  This may be one of hte "non-criculating item types" in a circulating location?

**Comment by kevinreiss** [comment]
https://catalog.princeton.edu/requests/11328329?mfhd=11026525&source=pulsearch
https://catalog.princeton.edu/catalog/10398425
