### ISSUE TITLE
Update Flash Message on Request Form

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#594]
Currently this text is displayed on the request form

Physical Delivery requests are not being accepted until at least 4/30 including Borrow Direct and Interlibrary Loan services.

Propose changing this to the following for non-pilot program users:

Physical Delivery requests are not being accepted until at least 6/8 including Borrow Direct and Interlibrary Loan services.

Propose using this for pilot users:

Only circulating materials from Firestone Library are eligible for pick-up. Physical Delivery requests for other Library locations are not being accepted until at least 6/8 including Borrow Direct and Interlibrary Loan services.

**Comment by christinach** [comment]
it look good to me.

**Comment by escowles** [comment]
👍 That looks good to me.
