### ISSUE TITLE
Non-Barcoded Serial Request

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#610]
This bib ID/holding combo presents a problem case:

1. A multi-volume/work record
2. No barcoded Items
3. User should be allowed to supply volume and issue if they can. 

https://catalog-staging.princeton.edu/requests/10574699?mfhd=10320354&source=pulsearch

Possible course of action
1. "Re-activate" the fill_in_field feature for this scenario so the user can supply the enumeration info if they do know it. 
2. Confirm with circ staff where the email notification of these should go for triage since they can't go through the hold request mechanism without a barcoded item. 
3. The error message states: Item Cannot be Recalled, see circulation desk. This should probably be something more generic.

**Comment by kevinreiss** [comment]
<img width="1330" alt="Screen Shot 2020-06-01 at 12 30 02 PM" src="https://user-images.githubusercontent.com/278825/83436542-a77bff80-a403-11ea-976f-484016969d3c.png">

**Comment by carolyncole** [comment]
This is now sending the recap error issue.  The html is really bad, I will look to make it nicer
![Screen Shot 2020-06-02 at 10.01.42 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/bfcd9e32-b513-48c2-a0eb-ac54b7cc3033)

**Comment by kevinreiss** [comment]
We should connect with circ staff to discuss what's best for their workflow for handling these edge requests for non-item materials.

**Comment by carolyncole** [comment]
We connected.  They do not want to do a title level hold.  They do want the emails to be sent out to trace@princeton.edu.  Will need to transition trace to fstpage once that has been activated.

The email should include information of the enumeration if the patron sends it.
