### ISSUE TITLE
Re-check Aria Roles

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#620]
In the quick work we've had to do with the request form a few regressions have crept in related to form accessibility. Ran the WAVE tool on the form with this URL

https://catalog.princeton.edu/requests/10574699?mfhd=10320354&source=pulsearch

and got some issues related to aria-labels.

**Comment by carolyncole** [comment]
Tested https://catalog.princeton.edu/requests/99106951903506421?mfhd=22498248020006421&source=pulsearch with lighthouse.
We have two aira errors:
Tthe check box for selected and the edd input form do not have unique ids.
![Screen Shot 2021-09-08 at 2 23 37 PM](https://user-images.githubusercontent.com/1599081/132564293-69ad8a46-e557-47a9-9c51-3673c541f169.png)
