### ISSUE TITLE
reopen marquand

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#645]
Should be available for scanning only.

**Comment by kevinreiss** [comment]
This location probably needs the most work. Marquand items located at ReCAP should be recap_edd only as well.

**Comment by kevinreiss** [comment]
Marquand on-site items are available for scanning only.

**Comment by carolyncole** [comment]
Here is a recap item that is marqaund only: https://catalog-staging.princeton.edu/requests/11780965?mfhd=11443781&source=pulsearch
Should only have edd, not pickup and edd...
