### ISSUE TITLE
Requesters are confused about when books are available to pickup

### ISSUE THREAD

**Issue by escowles** [pulibrary/requests#656]
When we sent reminder emails to patrons that they had books ready to pick up, some of them responded that they thought they were not available until 6/8 (which is the date we were planning to return the items to the shelf). Review the notification email wording for clarity and ambiguity.

**Comment by kevinreiss** [comment]
The email makes no mention at all of this date. 

It just states:

```Your request to pick this item up has been received. We will process the requests as soon as possible, but given the demand and the current circumstances some delay may occur. You will receive an email when the book is available for pick-up.```

Followed by the pick-up hours and covid safety protocols. All our public website communications and web banners all still reference the 6/8 as our "resumption of services". I'm not sure what we'd change in the email to alleviate the confustion.

**Comment by kevinreiss** [comment]
The notice voyager generates looks like this currently:
```The item(s) that you requested are now available at the location shown below. Please pick up the item(s) before the indicated expiration date.

Pick-up times at Firestone are 11am - 3pm, Monday - Friday.

Location:               .Firestone Library
Title:          My Book.
Author:         My Author.
Item ID:               xxxxxxxxx
Call #:        xxx 
Expiration Date:                6/11/2020

When picking up and/or dropping off your books, please do so promptly, remain only in the designated pick-up area, wear a mask or face covering, and follow social distancing guidelines. Please plan to limit your number of trips to the Library.

We appreciate your help in our efforts to slow the spread of Covid-19.

Sincere thanks.

If you have questions or need assistance contact us at fstcirc@princeton.edu
```

**Comment by escowles** [comment]
@kevinreiss Thanks — so it seems like "Expiration Date" is the only potentially ambiguous/confusing text here. Do we want to change that to "Pick Up By:" ?
