### ISSUE TITLE
A Marquand In Library Use Only with no items, should not allow for pickup

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#671]
https://catalog-staging.princeton.edu/requests/11129815?mfhd=10843240&source=pulsearch

**Comment by kevinreiss** [comment]
https://catalog-staging.princeton.edu/catalog/11129815 @mzelesky how can we have a Marquand item with no item record with an "Available" item status. Shouldn't it be in either in-process or on-order?
