### ISSUE TITLE
We should provide a cancellation confirmation

### ISSUE THREAD

**Issue by christinach** [pulibrary/requests#714]
When I cancel a request I would like to receive a cancellation confirmation email.

**Comment by kevinreiss** [comment]
It should be doing this already. If it isn't something is broken.

**Comment by mzelesky** [comment]
I think it would be helpful to have a cancellation email sent to circ staff. Christina cancelled a request earlier, but circ staff manually re-created the hold later.

**Comment by kevinreiss** [comment]
This email would be sent to circ if someone decides to cancel a hold request from the /account screen?

**Comment by christinach** [comment]
yes, this would make sure that the user wants to cancel a request.

**Comment by carolyncole** [comment]
Alma now sends these
