### ISSUE TITLE
Why does this one error?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#736]
https://catalog-staging.princeton.edu/requests/11226565?mfhd=10932852&source=pulsearch

**Comment by kevinreiss** [comment]
When sending in a digitization request to ILLiad

**Comment by christinach** [comment]
It wasn't indexed in solr-staging. I restarted nginx on bibdata-staging1 and indexed this bibid: 11226565.

**Comment by christinach** [comment]
I restarted ^ nginx because bibdata-staging had an error page.
