### ISSUE TITLE
Add TN to Digitization/ILLiad Confirmation Email

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#742]
Add the transaction number to the email template.

**Comment by kevinreiss** [comment]
Place this before the call number in the current template.

**Comment by carolyncole** [comment]
I had added the transaction number to the email, but now would be a good opportunity to determine what other clean up should be done...
![Screen Shot 2020-07-06 at 8 11 28 AM](https://user-images.githubusercontent.com/1599081/86591852-5ad69780-bf60-11ea-8b41-8cb66b1ca740.png)
