### ISSUE TITLE
Populate SSN and Number Fields When Creating an ILLIad User

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#744]
Inject patron barcode into SSN field (barcode needs to come out ldap it is not getting filled from patron)
Inject employee ID number in Number field

**Comment by kevinreiss** [comment]
Shouldn't bibdata give us the patron barcode? Or was a bug discovered there?

**Comment by carolyncole** [comment]
@kevinreiss I had already fixed this in the which is why I did not ticket it.  #740 was discovered while looking at this issue.
