### ISSUE TITLE
On Shelf Titles Highlight stackmap link

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#75]
On shelf titles should clearly route the user to the stackmap link and NOT display a pickup list widget. Example ID: 10005935

**Comment by sdellis** [comment]
Partial duplicate of #77

**Comment by sdellis** [comment]
This already lists the stackmap link. Closing as this is already fixed by #78

**Comment by sdellis** [comment]
Hmm... this may only be the case when it's requestable.traceable. Going to add another method for the stackmap url to display if on_shelf.
