### ISSUE TITLE
Online Titles Should Display Available Links

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#76]
Example ID: 9994692

Available links can be found in the solr doc key ```electronic_access_1display```

**Comment by sdellis** [comment]
Looking into this further and there are several outstanding questions... 

Question 1
What does the data structure look like for multiple URLs? Right now we get hashes like this from the `electronic_access_1display` field:
Example 1: `{\"http://www.jstor.org/stable/10.1525/j.ctt1ggjhp4\":[\"www.jstor.org\"]}`
Example 2: `{\"https://getit.princeton.edu/resolve?url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&rfr_id=info:sid/sfxit.com:opac_856&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&sfx.ignore_date_threshold=1&rft.object_id=954925427238&svc_val_fmt=info:ofi/fmt:kev:mtx:sch_svc&\":[\"getit.princeton.edu\",\"View Princeton's online holdings\"]}`

**Comment by tampakis** [comment]
For reference, here's the code that generates the hash: https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/princeton_marc.rb#L307-L340

the key in the hash is the actual URL to the item, the value for the hash key is an array. The first value in the array is the display text for the url. If there is a second value (ie "View Princeton's online holdings"), it is an additional label to appear before the actual link. Here's how it displays in the New Catalog: https://pulsearch.princeton.edu/catalog/9835493.

@kevinreiss probably knows how to answer the second question better, but it seem like the getit links should be pulled in via AJAX like they do in the New Catalog.

**Comment by tampakis** [comment]
It's always a single hash. There just may be multiple key, value pairs within the hash if there are multiple urls.

**Comment by kevinreiss** [comment]
Re: Question 2, we have two use cases.

1. Records in Orangelight with online links that start with "getit.princeton.edu". These are explicit look-ups for known full-text resources in the SFX knowledgebase, so we could potentially render these and reliably call them "online resources".
2. For other records with online links the link itself is the only one we can "reliably" call a full-text option right now. Other data that comes from umlaut relies on standard number lookups of third party sites like haithi-trust and google books that I'm not sure we want to present as canonical options for full-text on resources that already have one provided by our catalogers.
