### ISSUE TITLE
Change Pickup Location for Engineering Library Materials

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#767]
The Engineering Library is going to be servicing a new pick-up location in Fine Hall. All materials available for physical request at that Library should list this as the pickup location. The label will be "Engineering Library at Fine Hall". @mzelesky needs to work through some configurations in Voyager before this goes live, so wait on him confirming that has happened before making this change.

**Comment by carolyncole** [comment]
@mzelesky can this be closed based on a conversation you had with Willow Dresszel

**Comment by kevinreiss** [comment]
yes, this is resolved.
