### ISSUE TITLE
Reserve Item Isn't Requestable

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#768]
https://catalog.princeton.edu/requests/541697?mfhd=590470

The request form shows up with the correct digitization request option but the submit button is inactive.

**Comment by kevinreiss** [comment]
The item is permanently located in "sa" but is temporarily in "sar". Something related to a mismatch there is likely the root cause.

**Comment by carolyncole** [comment]
Seems to be working in the current version
