### ISSUE TITLE
'Request pickup or digitization' form does not list the item

### ISSUE THREAD

**Issue by christinach** [pulibrary/requests#770]
https://catalog.princeton.edu/requests/4105260?mfhd=4384522&source=pulsearch
https://bibdata.princeton.edu/bibliographic/4105260/items
the recap location has an item but it is not appearing in the pickup form.

**Comment by carolyncole** [comment]
You are filtering by MFHD, which mean you will only see the items in that location.  When you look at the unfilter URL (https://catalog.princeton.edu/requests/4105260) you see them both.
