### ISSUE TITLE
Holdings without item records and enumerated items should be allowed to be digitized

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#776]
See this item is has both types: https://catalog.princeton.edu/requests/2286894

![Screen Shot 2020-08-18 at 9 25 11 AM](https://user-images.githubusercontent.com/1599081/90518410-c0f43400-e134-11ea-9b19-11b8adf9ea23.png)
![Screen Shot 2020-08-18 at 9 25 05 AM](https://user-images.githubusercontent.com/1599081/90518418-c2bdf780-e134-11ea-9630-7cdd8bb25370.png)

**Comment by kevinreiss** [comment]
After speaking with Joan and Marie this type of item should make both digitization and pick-up request options available to the patron when appropriate.

**Comment by carolyncole** [comment]
I assume using the same format as the "normal" form would be most appropriate?  @axamei @kevinreiss 
![Screen Shot 2020-08-19 at 10 56 52 AM](https://user-images.githubusercontent.com/1599081/90792368-63005180-e2d8-11ea-8752-84a8265bd746.png)

**Comment by kevinreiss** [comment]
Yes, as much as we can let's keep the forms uniform.

**Comment by carolyncole** [comment]
I am putting a pause on this work to tackle another ticket need for Monday.  This was a nice to have.  We also have to get in contact with Liza and Nick to figure out if we should be putting in Illiad transactions for local books, and Marie and Joan to find out who we should be sending emails to for Recap.
