### ISSUE TITLE
In process Items and On Order Items should be requestable for digitization

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#777]
They have request only options currently, but should we have digitization?
![Screen Shot 2020-08-18 at 9 37 06 AM](https://user-images.githubusercontent.com/1599081/90519751-6bb92200-e136-11ea-8060-fd445faf2af7.png)
![Screen Shot 2020-08-18 at 9 36 33 AM](https://user-images.githubusercontent.com/1599081/90519755-6d82e580-e136-11ea-8f4c-c1a327c573e4.png)

**Comment by kevinreiss** [comment]
Per Joan and Marie, on order items should NOT be available for digitization. For now In Process items should also NOT be available. They will check with 693 if digitization of these items might be feasible.
