### ISSUE TITLE
Form should not allow physical requests of Columbia items

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#790]
See: https://github.com/pulibrary/orangelight/issues/2206

The form should only show digitization not pickup.

Here is one that should not show the option for pickup: https://catalog.princeton.edu/catalog/SCSB-9161184

**Comment by tpendragon** [comment]
https://catalog.princeton.edu/catalog/SCSB-3085213 does work correctly now that we've disabled circulation for SCSBCUL.
