### ISSUE TITLE
Utilize the Marc Liberation Hathi Status endpoint To not allow pickup requests  for collumbia

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#791]
Refs https://github.com/pulibrary/marc_liberation/issues/758

Instead of just disallowing all 'scsbcul' items check the endpoint and if the response is "DENY" we must deny pickup.

**Comment by hackmastera** [comment]
In testing, this won't really look right until https://github.com/pulibrary/marc_liberation/issues/764 is done, but that shouldn't be done in prod until this is merged / deployed.
