### ISSUE TITLE
ETAS Illiad items are sending the wrong Location

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#815]
Here is a normal Forrestal annex request.  You can see in the for right the location field is set to Forrestal
![Screen Shot 2020-09-10 at 9.36.25 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/45c0bf9f-860c-45f6-a77d-fbf430479df3)

Here is an ETAS Forrestal Annex request.  You can see the location is set to Hathi.
![Screen Shot 2020-09-10 at 9.34.52 AM.png](https://images.zenhubusercontent.com/5c925e2d9d1bd30b8d310436/84111ef0-b940-4df3-ab6a-caf59edd2eff)

Is there any advantage to knowing these are ETAS items?

**Comment by kevinreiss** [comment]
ETAS going away summer 2021.
