### ISSUE TITLE
Restrict On Campus Services to Users Authorized to Be On Campus

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#822]
- [x] Create a new database table in marc liberation to contain the list of netids for those users who are eligible to be on campus
- [x] Create rake task that can be regularly used refresh the database table
- [x] Add a boolean "campus_authorized" attribute to the response returned the "/patron/{netid}" route in marc liberation
- [x] Leverage the new "campus_authorized" attribute to suppress both pick-up and on campus in library use requests for users where this value is negative.

**Comment by carolyncole** [comment]
Pickup and in library use should fail silently to begin with.

**Comment by kevinreiss** [comment]
After some discussion we are thinking that for users who do not show up as "campus authorized" we should print up a flash message when the form loads that states:

```You are not currently eligible for on-campus services at the Library. Please consult with your Department if you believe you should have access to these services.```
