### ISSUE TITLE
AEON items should never show help me get it in the form

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#872]
https://catalog.princeton.edu/requests/4646682?mfhd=4880442&source=pulsearch is a RBSC item, we should just always serve up the Aeon options for that irregardless of status. Also when we show this message : "Only items available for digitization can be requested when you do not have a barcode registered with the Library" to unauthenticated users maybe we should just encourage them to sign in, I was a bit confused when I saw this message since I have an active barcode.

**Comment by kevinreiss** [comment]
@carolyncole I will confirm with SC staff that don't want any contextual behavior by type of user on the Aeon items. In normal times 50% of their users don't have PU accounts.

**Comment by carolyncole** [comment]
AEON requests do not force a login during the request process, so we do not have accurate information about the user.   When they are already logged in the form works.  When the have not yet logged in the form does not work.  We should ignore the user for AEON.
