### ISSUE TITLE
BorrowDirect Widget not displaying when it should

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#88]
Animated gif spinner is also returning a 404.

**Comment by kevinreiss** [comment]
I believe the spinner needs to be referenced with the asset_path('requests/spinner.gif') helper in the view html and the asset pipeline needs to be told about it in config/initializers/assets.rb of the application hosting the engine to properly feed it into the asset pipeline. There might be a better place for that in the actual engine code, but is what made the 404 error go away for me

Rails.application.config.assets.precompile += %w( requests/spinner.gif )

When I visit a current example for borrow direct at /requests/1788796?mfhd=2053005&source=pulsearch I can see that the callback is working and the HTML is updated to include the borrow direct request form. However for some reason it isn't rendered in the browser.
