### ISSUE TITLE
Update unavailable_statuses, on_order?, and in_process? to match alma

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/requests#891]
Once we know what statuses we will get out of alma, we will need to update the list here:

https://github.com/pulibrary/requests/blob/1a0c830f272cd2a9705c47c8842fdcefdd70dd11/app/models/requests/requestable/item.rb#L173-L179

As part of this, split this array into 2 so that we know which statuses are from the ILS and which are from SCSB.

We may want to also add an explicit check for an "available" status in the `charged?` method here:
https://github.com/pulibrary/requests/blob/1a0c830f272cd2a9705c47c8842fdcefdd70dd11/app/models/requests/requestable/item.rb#L69-L71

so that if the above list isn't complete for some reason we still know that those items can be requested.

Note that `charged?` has evolved to mean "anything unavailable that's not in-order or in-process"

`on_order?` and `in_process?` may need to be updated as well and are defined here: https://github.com/pulibrary/requests/blob/1a0c830f272cd2a9705c47c8842fdcefdd70dd11/app/models/requests/requestable.rb#L118-L126

**Comment by kevinreiss** [comment]
@carolyncole I think we have these two cases handled now.

**Comment by kevinreiss** [comment]
The "Acquisition" Process is a stand-in for "on order" titles. Handled properly

https://catalog-alma-qa.princeton.edu/requests/9987745643506421?mfhd=2246361240006421&source=pulsearch

**Comment by kevinreiss** [comment]
"In Process" Items under the "acquisition technical services" work order type are handled properly.

https://catalog-alma-qa.princeton.edu/requests/99371663506421?mfhd=22157583630006421&source=pulsearch

**Comment by kevinreiss** [comment]
I think we can close this one.
