### ISSUE TITLE
Marquand library is closing and items will be off site

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#892]
Moving books to Clancy will start happening March 29th, Rare books will happen on March 1st.
Certain location codes should always be request-able to a Firestone Reading room.

1. Non barcoded Marquand item 
   * Voyager may not know about the the barcode, so we will just need to also send an email about a non barcoded item (already exists for regular non barcoded item).
   * Going to recap problems is ok
   * We may need to send another email for Marquand only non barcoded items.
2. Barcoded Marquand Item
      * Items will be moving to an offsite location over time.  For  Marquand items that are non supervised (SA and others), we will need to query Clancy (https://www.clancymoving.com/commercial/library-services/book-storage/):
          * if the item succeeds and (not an E-request?) we will need to send a notification to Marquand email address that the book is on its way.  Add a hold request (like a pickup) in Voyager (will need to be converted to Alma).  
          * If the call fails send the a notification to Marquand the Marquand staff to go find the item in the Marquand Library or at 693, or on a truck

When they close the doors there will be 6-8 weeks for the items to be moved to the new location.
    
SA-location is all going to the offsite facility (in library use only). These can only be delivered to Firestone Marquand Room
    * Items will need to be requested from an offsite location (Clancy) for certain Marquand location.
         Items in the off site facility will be requested to 693, prepared in 693 and then shipped to Firestone for the patron to use in house.

SAX- location will be in Firestone Rare Books.  These will be in a new location, because some of the items are going to 693 in addition to Firestone.
    * Rare Books from Marquand will be in a separate room from the regular collections.
    * A new location will need to be added in marc_liberation and marked as Aeon

Other Marquand locations - We do not yet know where these are going, maybe 693

API is run by https://www.caia-solutions.com/
**API key for Clancy is in Last Pass**
https://portal.caiasoft.com/apiguide.php

Dev Caiasoft: https://play.caiasoft.com
Prod Clancy Caiasoft: https://clancy.caiasoft.com

Marquand Locations map: https://docs.google.com/spreadsheets/d/1wo8SGzh_t5VrX4rpjzLZt0YeCnU2_8WphZX-JdCIqVw/edit#gid=0
Sample barcodes in caiasoft dev system for: https://docs.google.com/spreadsheets/d/1JB-Dn0aNWwX0N8_KXOU_ORM6XFzPvuY3utdc1DMQT2M/edit#gid=0

**Open Questions:**
* What happens when items are on a truck?
* What is the final location list?  Define Others and where they will be
* ~~Clancy will do EDD~~ Clancy facility will not do EDD, we need to confirm if Marquand will do onsite EDD when items are shipped back to campus?
     * ~~Assume ERT request (https://portal.caiasoft.com/apiguide.php?serv=restapi&rec=3&oper=circrequests )~~

**Comment by kevinreiss** [comment]
For voyager hold requests on the "sa" location Marquand circk desk pick-up information will be (from @mzelesky): 

```The code for the circ desk is 'sacirc', which is location_id 321```

**Comment by carolyncole** [comment]
@kevinreiss Just to be certain I have all the cases correct.
For In Library Use:
   * Available, in Clancy
       1. request from clancy 
       1. Add hold to 'sacirc' 
   * Not Available, in Clancy
       1.  Email Marquand
   * Available, not in Clancy
       1. Add hold to 'sacirc' 
   * Not Available, not in Clancy
       1.  Email Marquand

What should we do about the small number of circulating items?

I believe at this point we do not know about digitizing.

**Comment by kevinreiss** [comment]
I think these are all correct.

**Comment by kevinreiss** [comment]
Email template request for physical requests: https://drive.google.com/file/d/1kkIkPrBEWtN5U9bC3VhaIZ38_xO253Wy/view?usp=sharing.

**Comment by kevinreiss** [comment]
Features all implemented.
