### ISSUE TITLE
Swap Form to show available options for an available status

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#896]
Instead of looking at all the unavailable status codes first, we should check if an item is available.  This will make it easier to migrate the available items to Alma

**Comment by kevinreiss** [comment]
Is this something we still want to try and address at some point?

**Comment by carolyncole** [comment]
I'd say this is done (or done enough for now) https://github.com/pulibrary/requests/blob/main/app/models/requests/requestable/item.rb#L75
