### ISSUE TITLE
What happens when Alma has a barcode but it is not real (i.e Holdings with no attached item records)

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#897]
Does this cause issues with ReCap?

Something to check for in process and on order.

**Comment by kevinreiss** [comment]
Examples we need to provide
1. On Order Record
2. In Process Record
3. Circulating Shelved holdings that aren't barcoded
4. Partially barcoded multi-volume sets
5. Special Collections holdings that aren't barcoded

**Comment by kevinreiss** [comment]
I think we need to spend some testing this scenario.

**Comment by kevinreiss** [comment]
Annex Item: https://catalog-alma-qa.princeton.edu/requests/9915485853506421?mfhd=22272080260006421&source=pulsearch

Falls back appropriately.

**Comment by kevinreiss** [comment]
Firestone Item: https://catalog-alma-qa.princeton.edu/requests/998820893506421?mfhd=22272042640006421&source=pulsearch

Falls back appropriately

**Comment by kevinreiss** [comment]
I think we are in good shape with this use case.
