### ISSUE TITLE
Add Feature Test(s) to Confirm SCSB CUL AR and MR items go to the right pick-up 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#904]
We have an override on the pick-up location for SCSB Items from CUL's "AR" Collection Code to be shipped only to Marquand. We also have an override to send "MR" collection items to Mendel. 

Right now these items seem to be getting the default scsb item treatment of having a pick-up only at Firestone. Example record:

https://catalog.princeton.edu/requests/SCSB-5595350

The override code is here: https://github.com/pulibrary/requests/blob/d2855bd8ca0019ca9f389e44433328dd4bcc3650/app/models/requests/requestable.rb#L182-L200. 

These items are routing through 693 like others Marquand materials so we should try match the form labels for delivery restrictions message (i.e. 2-4) business like we have on this record:

https://catalog.princeton.edu/requests/8539933?mfhd=8285657

**Comment by carolyncole** [comment]
We should add a feature test to make sure this will work into the future.
