### ISSUE TITLE
ReCAP Flag Should be calculated using the remote storage flag

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/requests#918]
All holding locations in Alma can now be assigned a "remote_storage" attribute. All locations with materials stored at ReCAP will now have this value set as "recap_rmt". Instead of checking the library location to note if a requestable item is at ReCAP this value should be checked. See https://github.com/pulibrary/bibdata/pull/1302 for the addition of the attribute. 

The main functional change between Alma and Voyager relates to ReCAP holding locations that are allowed to be shipped only to a certain library. These holding loctions will now be explicitly marked as being located within the Library they can be shipped to but will have the remote storage attribute set to know the items need to be routed through the ReCAP request process. Example: 

Recap items that can only be requested to Lewis will be marked as being in Lewis and flagged with offsite.
This will be the case for any of the specialty locations that can only be delivered to certain libraries.

Recap items that can be requested to any library will still be marked as in the recap library, but will also have the remote storage attribute set.

**Comment by kevinreiss** [comment]
In order for SCSB to work with PUL items that are shelved in a remote_storage location when the request is placed it needs to:

1. Place a SCSB Physical Item Request for the item in question
2. If that is successful, place an Alma hold request for the same item. These requests should be identical to the hold requests that will be placed in Alma when this ticket is complete: https://github.com/pulibrary/requests/issues/933.

**Comment by kevinreiss** [comment]
mendel$pk is the only location with remote_storage="recap_rmt" catalog-alma-qa that has some items in it. 

https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Badvanced_location_s%5D%5B%5D=mendel%24pk&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search
