### ISSUE TITLE
Temp holding location test fails over missing email field 

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#925]
"Temporary Shelf Location displays the temporary holding location library label" feature test fails over a missing email address field.

https://github.com/pulibrary/requests/blob/main/spec/features/requests/request_spec.rb#L59-L77

Alma item ID: 9999443553506421

**Comment by kevinreiss** [comment]
When this PR is merged and deployed to alma qa https://github.com/pulibrary/orangelight/pull/2465 we can take another look. @sdellis This should provide us a mms_id and mfhd to send to the form.
