### ISSUE TITLE
Create Test Case for Physical Reserves

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#926]
This test is failing and may need a new item that is on reserve:
https://github.com/pulibrary/requests/blob/main/spec/models/requests/request_spec.rb#L273-L278

**Comment by kevinreiss** [comment]
If we decide to continue physical reserves we'll need a test case here.

**Comment by kevinreiss** [comment]
Spec passes now, but we should test this in the qa catalog.

**Comment by kevinreiss** [comment]
Example MMS ID on Reserve: https://catalog-alma-qa.princeton.edu/catalog/9990845423506421

Need to bring up at Alma/Blacklight Check-in

**Comment by kevinreiss** [comment]
Any items that have on_reserve set to "Y" should not be requestable at all even for scanning. The best case here is to suppress the request button on the catalog page for these items. 

Another example:
https://catalog-alma-qa.princeton.edu/requests/997344323506421?mfhd=22122578740006421&source=pulsearch

Full Availability returned for that item. 
https://bibdata-alma-staging.princeton.edu/bibliographic/997344323506421/holdings/22122578740006421/availability.json

**Comment by kevinreiss** [comment]
The catalog page for reserve items now updates the location correctly, https://catalog-alma-qa.princeton.edu/catalog/997344323506421, we either need to suppress the request button or handle reserve behavior in the form (right now the fallback option on the form says the item is available for digitization but not loan). I will check with circulation staff on what the best outcome is. This is something we don't have to have fully worked out at go live, but do need in place by the middle of August.

**Comment by carolyncole** [comment]
Orangelight is not sending the user to requests, so we can close this.
