### ISSUE TITLE
Test Thesis Requesting

### ISSUE THREAD

**Issue by sdellis** [pulibrary/requests#927]
https://github.com/pulibrary/requests/blob/main/spec/models/requests/request_spec.rb#L365-L417

**Comment by kevinreiss** [comment]
Blocked until thesis collection indexed in alma-qa for testing.

**Comment by christinach** [comment]
@kevinreiss thesis collection is indexed in alma-qa https://github.com/pulibrary/bibdata/issues/1276

**Comment by kevinreiss** [comment]
Thanks, we can give this a shot now.

**Comment by kevinreiss** [comment]
Thesis records from dspace look they are working well.
