### ISSUE TITLE
Attempt to call `#errors` on record array

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/requests#974]
It seems like the validation code doesn't expect or allow for multiple records to be requested at once.
https://app.honeybadger.io/projects/54399/faults/79669963

`NoMethodError: undefined method `errors' for #<Array:0x00007f1af7e88280>`

https://github.com/pulibrary/requests/blob/a7eb77eb108a583d502102e5dfc884b0af20b0ce/app/models/requests/selected_items_validator.rb#L36

**Comment by kevinreiss** [comment]
There is no reason multiple items can't be requested. I suspect there is probably a data issue at play here.

**Comment by carolyncole** [comment]
I tested ordering multiple items from https://catalog.princeton.edu/requests/99106951903506421?mfhd=22498248020006421&source=pulsearch There were no errors
