### ISSUE TITLE
Enumeration Sort is Off

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#987]
Sorting of enumerated values isn't coming through properly:

Example from Science:

https://catalog-alma-qa.princeton.edu/requests/998574693506421?mfhd=22153448500006421&source=pulsearch

**Comment by kevinreiss** [comment]
may be connected to https://github.com/pulibrary/orangelight/issues/2463. @axamei @carolyncole do you recall if we relied on datatables to sort this, or did voyager send back things ordered correctly?

**Comment by kevinreiss** [comment]
Now that datatables has been restored we should look at how this behaves with that back in place.

**Comment by kevinreiss** [comment]
The display is much better with datatables restored but there are still some oddities, in this record volume 360 should be at the top of the sort upon page load and vol 358 is. 360 is farther down on the page.

**Comment by hectorcorrea** [comment]
The Alma API for items for a given holding (GET /almaws/v1/bibs/{mms_id}/holdings/{holding_id}/items) does provide an option to [sort by a given field](https://developers.exlibrisgroup.com/alma/apis/docs/bibs/R0VUIC9hbG1hd3MvdjEvYmlicy97bW1zX2lkfS9ob2xkaW5ncy97aG9sZGluZ19pZH0vaXRlbXM=/). There is no default sort order.

One the API is available again we can tweak BibData to return the list sorted (by enum? by chron?) and see how it looks in Request.
