### ISSUE TITLE
Mendel Remote Storage Locations Fail to Place Hold

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#989]
Believe this is an alma config issue related to mendel$pk and mendel$qk locations. Hold requests also fail when you try to create them in the Alma Backend. 

@mzelesky @pmgreen we'll have to do more testing of these next week.

**Comment by kevinreiss** [comment]
Created a hold in alma backend successfully using this bib/holding combo

MMS ID: 99112325153506421
Holdings ID: 22270490570006421

Try this again (when SCSB UAT is available)

**Comment by kevinreiss** [comment]
Right now this shows the in library use option (with the translation error mentioned in #990) but sends the requests into illiad.

**Comment by carolyncole** [comment]
Items that are ReCap but are not should be put into the in process state.
