### ISSUE TITLE
Mendel ReCAP Remote Storage Locations Show Help Me Get IT

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#990]
Example https://catalog-alma-qa.princeton.edu/requests/996303883506421?mfhd=22166625550006421&source=pulsearch

impacts mendel$pk and mendel$qk. 

They are winding up in this case under calculate_recap_services

https://github.com/pulibrary/requests/blob/alma/app/models/requests/router.rb#L100

**Comment by kevinreiss** [comment]
Still an active issue. #991 is a duplicate.

**Comment by carolyncole** [comment]
@kevinreiss the recap_edd flag is set wrong in bibdata.  It is set to false in all cases.  This means we will not ask for edd, and can only ask for help me get it.  I will open a ticket in bibdata

**Comment by carolyncole** [comment]
Depends on https://github.com/pulibrary/bibdata/issues/1498

**Comment by kevinreiss** [comment]
Looks like we are getting the in library use option now which is correct, but there is a missing translation file with the switch to remote storage. 

![Uploading Screen Shot 2021-07-12 at 5.40.04 PM.png…]()

**Comment by carolyncole** [comment]
The mendel one is really strange because production bibdata does not have a location that does not criculate for recap mendel.  This may be a bibdata flag issue again.

**Comment by kevinreiss** [comment]
I think some of these are set at the item level to NoCirc and that is kicking in to show "in library use".
